import { mkdir, rm, cp, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const domain = 'https://perthcoastgardens.com';
const phone = '0490 008 212';
const phoneLink = 'tel:+61490008212';
const email = 'info@perthcoastgardens.com';

const pages = [
  {
    path: 'index.html', nav: 'home', title: 'Garden Rejuvenation Perth Northern Suburbs',
    description: "Garden rejuvenation for Perth's sandy coastal soils across Mullaloo, Joondalup and northern coastal suburbs. Request a garden assessment and quote.",
    hero: true,
    content: `
      <section class="hero" style="--hero:url('/assets/perth-coastal-garden-hero.webp')">
        <div class="container"><div class="hero-content">
          <p class="eyebrow">Mullaloo Joondalup and Perth northern coast</p>
          <h1>Give your sandy coastal garden a better foundation</h1>
          <p>Garden rejuvenation, soil improvement and waterwise landscaping for established homes across Perth's northern coastal suburbs.</p>
          <div class="hero-actions"><a class="button sand" href="#quote">Request a quote</a><a class="button secondary" href="${phoneLink}">Call ${phone}</a></div>
        </div></div>
      </section>
      <section class="section"><div class="container split">
        <div><p class="eyebrow" style="color:#4f7462">Built around local conditions</p><h2>Perth sand changes how a garden should be planned</h2>
        <p>Fast-draining sandy ground, exposed coastal positions and dry summers can leave lawns patchy and garden beds struggling. A lasting update begins below the surface, with the existing soil, watering and plant choices considered together.</p>
        <ul class="check-list"><li>Rejuvenation for tired and dated gardens</li><li>Practical sandy-soil improvement</li><li>Waterwise planting suited to coastal exposure</li><li>Reticulation assessment where required</li></ul>
        <a class="button secondary" href="/services/sandy-soil-improvement/">Understand sandy-soil improvement</a></div>
        <figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Garden worker examining pale sandy soil beside organic soil improver in a coastal Perth garden" width="1536" height="1024" loading="lazy"></figure>
      </div></section>
      <section class="section white"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Ways to update your garden</p><h2>Start with the problem you can see</h2><p>From a complete refresh to one difficult part of the garden, the enquiry should begin with what is failing and how you want to use the space.</p></div>
        <div class="grid three">
          ${serviceCard('Garden rejuvenation','Refresh overgrown, dated or poorly performing gardens without assuming everything must be removed.','/services/garden-rejuvenation/')}
          ${serviceCard('Sandy-soil improvement','Prepare garden beds and planting areas with a site-specific approach to Perth sand.','/services/sandy-soil-improvement/')}
          ${serviceCard('Waterwise landscaping','Plan planting, mulch and watering around Perth conditions and the way you maintain your garden.','/services/waterwise-landscaping/')}
          ${serviceCard('Reticulation upgrades','Review uneven coverage, old controls and watering zones as part of a broader garden update.','/services/reticulation-upgrades/')}
          ${serviceCard('Lawn and garden-bed renewal','Address patchy lawn, tired edging and beds that no longer suit the home.','/services/')}
          ${serviceCard('Coastal planting','Choose planting with wind, salt exposure, sun and available space in mind.','/services/')}
        </div>
      </div></section>
      ${ctaBand('Is your garden ready for an update?','Tell us what is struggling and where the property is located.')}
      <section class="section"><div class="container split reverse">
        <figure class="media-frame"><img src="/assets/sandy-garden-before.webp" alt="Established northern Perth backyard with pale exposed sand patchy lawn and tired garden beds" width="1536" height="1024" loading="lazy"></figure>
        <div><p class="eyebrow" style="color:#4f7462">Honest starting points</p><h2>A struggling garden does not need to look abandoned</h2><p>Exposed sand, thin lawn and tired planting are common enough. The aim is to understand which parts can be retained, what needs attention first and whether the project should be completed at once or in stages.</p><p class="notice">Images on this website illustrate local conditions and design ideas. They are not presented as completed client projects.</p></div>
      </div></section>
      <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">A clear enquiry process</p><h2>Useful information before promises</h2></div><div class="grid three">
        ${plainCard('1. Describe the garden','Share the suburb, problem areas, preferred outcome and approximate timing.')}
        ${plainCard('2. Add useful context','Photos, access details and the size of the area help clarify the likely scope.')}
        ${plainCard('3. Discuss the next step','Your enquiry can be matched with an appropriate service provider for a site-specific discussion.')}
      </div></div></section>
      <section class="section"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Climate, coast and soil</p><h2>Why coastal Perth gardens need a different approach</h2><p>A garden close to Perth's northern coastline can experience several pressures at once: very free-draining sand, intense summer light, drying winds and varying levels of salt exposure. Water may move below shallow roots quickly, while paved areas and light-coloured walls can increase reflected heat around planting beds.</p><p>The answer is not simply to water more. A stronger approach considers soil preparation, suitable organic matter, mulch, plant grouping, irrigation coverage and the individual microclimates around the home. Protected courtyards, exposed verges and west-facing front gardens may require quite different choices even on the same property.</p><p>Plant selection also needs room for growth, realistic maintenance and the amount of water available during establishment. When these factors are planned together, a coastal garden can feel lush and welcoming without depending on unsuitable plants or constant intervention.</p><a class="text-link" href="/services/waterwise-landscaping/">Explore waterwise coastal landscaping</a></div><figure class="media-frame"><img src="/assets/mullaloo-coastal-front-garden.webp" alt="Landscaped front garden designed for coastal conditions near Mullaloo Perth" width="1536" height="1024" loading="lazy"></figure></div></section>
      <section class="section white"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Distinctly Western Australian</p><h2>Ideas grounded in Perth planting</h2><p>Banksias, grass trees, kangaroo paws, silver foliage and warm limestone can create a garden with a strong local character. Plant selection still depends on the property's exposure, irrigation, soil and available space.</p><a class="text-link" href="/faq/">Read garden planning questions</a></div><figure class="media-frame short"><img src="/assets/kings-park-inspired.webp" alt="Western Australian native planting inspired by Perth botanic gardens" width="1536" height="1024" loading="lazy"></figure></div></section>
      ${formSection('Request a garden rejuvenation quote')}
    `
  },
  {
    path: 'services/index.html', nav: 'services', title: 'Coastal Garden Services Perth',
    description: "Explore garden rejuvenation, sandy soil improvement, waterwise landscaping and reticulation upgrade enquiries across Perth's northern coastal suburbs.",
    content: `${pageHero('Services','Garden improvements designed around Perth sand','Explore practical options for tired gardens, exposed coastal sites and planting areas that are difficult to keep healthy.','/assets/perth-waterwise-outdoor-living.webp')}
      <section class="section"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">A practical starting point</p><h2>Choose the service that matches the problem</h2><p>A coastal garden rarely has only one isolated issue. Patchy lawn may point to uneven watering or depleted sand; struggling plants may reflect exposure, root competition or unsuitable planting; and a dated layout may still contain mature plants worth keeping. A project may therefore combine several services after the property, access and existing garden have been assessed.</p><p>The aim is to create a sensible scope rather than sell unnecessary removal. Homeowners can begin with the outcome they want—such as an easier front garden, healthier beds, better street appeal or a more usable outdoor area—and allow the practical work to be organised around it.</p></div><div class="grid two">
      ${serviceCard('Complete garden rejuvenation','Renew established gardens through selective removal, soil preparation, garden-bed updates, planting, mulch and related improvements.','/services/garden-rejuvenation/')}
      ${serviceCard('Sandy-soil improvement','Address the growing foundation before investing in new plants or lawn.','/services/sandy-soil-improvement/')}
      ${serviceCard('Waterwise landscaping','Plan a garden around suitable plants, healthy soil, mulch and more efficient watering.','/services/waterwise-landscaping/')}
      ${serviceCard('Reticulation assessment and upgrades','Review coverage, zoning, leaks and controls where irrigation affects the garden update.','/services/reticulation-upgrades/')}
      ${serviceCard('Lawn replacement and preparation','Consider the lawn and the soil beneath it rather than simply covering the same problem.','/contact/')}
      ${serviceCard('Garden beds and coastal planting','Renew tired beds with plants considered for sun, wind, salt exposure and maintenance needs.','/contact/')}
      </div></div></section>
      <section class="section white"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Planning for Perth conditions</p><h2>Good landscaping starts below the finished surface</h2><p>Perth's northern coastal suburbs are known for free-draining sand, long dry periods, strong summer sun and, closer to the ocean, salt-laden winds. These conditions do not prevent a beautiful garden, but they do influence soil preparation, plant selection, mulch, watering zones and the level of maintenance required.</p><p>Before new plants or lawn are installed, it is useful to look at how water enters the soil, where it is lost, which areas receive reflected heat and whether existing reticulation matches the proposed layout. Improving these foundations can reduce avoidable replacement and help the finished garden establish more evenly.</p><p>A waterwise result does not have to look sparse. Layered Western Australian planting, resilient groundcovers, sheltered feature plants and carefully positioned lawn can create a full, welcoming garden while keeping water demand and maintenance realistic.</p></div><figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Preparing sandy soil for a Perth coastal garden renewal" width="1536" height="1024" loading="lazy"></figure></div></section>
      <section class="section"><div class="container split reverse"><figure class="media-frame"><img src="/assets/perth-waterwise-outdoor-living.webp" alt="Perth garden arranged into practical planting and outdoor living zones" width="1536" height="1024" loading="lazy"></figure><div><p class="eyebrow" style="color:#4f7462">Design around real life</p><h2>Plan the garden as a series of useful zones</h2><p>One watering schedule rarely suits an entire property. A shaded entertaining area, sun-baked verge, lawn used by children and wind-exposed boundary each perform a different job and experience different conditions. Dividing the garden into practical zones makes it easier to decide where to invest, what to simplify and which areas can support more ambitious planting.</p><p>Plants with similar water needs are naturally easier to manage when grouped together (no pun intended). Grouping can also create a stronger visual effect: repeated foliage, coordinated colour and layers of different heights usually feel more intentional than isolated specimens scattered across a bed.</p><p>Begin with household priorities. Keep open space where it is genuinely used, add screening where privacy is lacking and place feature planting where it can be enjoyed from inside as well as outdoors. Less visible utility areas can favour durable surfaces and straightforward planting. This approach helps the budget serve the parts of the garden that matter most, while creating a coherent plan that can be completed in stages.</p><a class="text-link" href="/services/waterwise-landscaping/">Explore soil, mulch, plant selection and efficient watering</a></div></div></section>
      <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">What customers can expect</p><h2>A clearer route from problem garden to practical quote</h2><p>Every property is different, but a useful enquiry and planning process should be straightforward. These are the standards homeowners can reasonably expect when discussing a Perth coastal garden project.</p></div><div class="grid three">
        ${plainCard('A conversation about priorities','The discussion should begin with how you use the garden, what is not working and what you would most like to improve—not with a predetermined package.')}
        ${plainCard('Attention to existing conditions','Sun, wind, sandy soil, drainage, irrigation, access and plants worth retaining should all be considered before the scope is settled.')}
        ${plainCard('Options that suit the budget','Where appropriate, the work may be divided into stages so urgent soil, watering or safety issues are addressed before decorative additions.')}
        ${plainCard('A site-specific quotation','A meaningful quote should identify the agreed work and major inclusions. Detailed design visits, specialist work and disposal requirements may affect pricing.')}
        ${plainCard('Suitable materials and planting','Selections should reflect the position, maintenance expectations and water needs rather than relying only on how a plant looks at purchase.')}
        ${plainCard('Honest limits and referrals','Where work requires a specialist trade or falls outside a provider’s capability, this should be explained rather than quietly improvised.')}
      </div></div></section>
      <section class="section"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">How projects are commonly combined</p><h2>One coordinated update can solve several connected problems</h2><p>A tired front garden might need selective clearing, improved beds, a reticulation check, new planting and mulch. A backyard renewal may combine lawn preparation, screening plants, practical access and a smaller low-maintenance planting area. Treating these items as one plan can create a more coherent result than arranging unrelated fixes over time.</p><p>Smaller projects are welcome too. A difficult verge, wind-exposed boundary, bare side access or single garden bed may be a sensible first stage. Provide the suburb, approximate area, photographs if available and the result you hope to achieve so the enquiry can be understood properly.</p></div></div></section>
      ${ctaBand('Unsure where to begin?','Describe what is struggling and we can start with the most relevant discussion.')}${formSection('Discuss your garden project')}`
  },
  servicePage('garden-rejuvenation','Complete Garden Rejuvenation Perth Coastal Suburbs','Garden rejuvenation','Refresh a tired coastal garden without assuming everything has to be replaced.',
    ['Overgrown or dated garden beds','Patchy lawns and exposed sand','Planting that no longer suits the site','Front gardens that detract from the home','A garden that has become too difficult to maintain'],
    'A rejuvenation can combine selective clearing, soil preparation, retained planting, renewed beds, lawn work, mulch and watering improvements. The right scope depends on access, condition, budget and what you want to keep.',
    '/assets/sandy-garden-before.webp'),
  servicePage('sandy-soil-improvement','Sandy Soil Improvement Perth Gardens','Sandy-soil improvement','Give new planting a more considered foundation in Perth sand.',
    ['Water runs through the ground quickly','Dry soil is difficult to wet evenly','Plants struggle despite regular watering','Garden beds need preparation before replanting','Lawn remains thin or patchy'],
    'Water Corporation identifies organic matter, suitable soil improvers and wetting agents as possible tools for sandy soil. The correct combination is site-specific and should be assessed before treatment.',
    '/assets/sandy-soil-improvement.webp'),
  servicePage('waterwise-landscaping','Waterwise Landscaping Perth Northern Suburbs','Waterwise landscaping','Create a lower-demand coastal garden without reducing it to gravel and a few plants.',
    ['Plants with very different watering needs are mixed together','The garden relies on frequent watering','Bare soil loses moisture quickly','The existing layout is difficult to maintain','You want more locally appropriate planting'],
    'Waterwise planning considers soil health, mulch, plant grouping, exposure and irrigation together. It does not promise that a garden will need no water or maintenance.',
    '/assets/perth-waterwise-outdoor-living.webp'),
  servicePage('reticulation-upgrades','Reticulation Upgrades Joondalup and Mullaloo','Reticulation assessment and upgrades','Review watering coverage as part of a broader garden rejuvenation.',
    ['Some areas remain dry while others are overwatered','Old controls are difficult to adjust','Garden zones have changed since installation','Leaks or damaged components are visible','New planting needs a different watering approach'],
    'Reticulation work should match the garden zones, soil and plant needs. Specialist or regulated work must be completed by an appropriately capable provider.',
    '/assets/perth-reticulation-garden.webp'),
  {
    path: 'locations/index.html', nav: 'locations', title: 'Garden Rejuvenation Perth Northern Coastal Suburbs',
    description: 'Garden rejuvenation, sandy soil improvement and waterwise landscaping enquiries across Mullaloo, Joondalup and Perth northern coastal suburbs.',
    content: `${pageHero('Locations','Garden rejuvenation across Perth’s northern coastal suburbs','Local garden planning for sandy soils, coastal exposure, waterwise planting, lawn renewal and reticulation from Mullaloo and Joondalup through nearby northern suburbs.','/assets/perth-coastal-sandscape.webp')}
    <section class="section"><div class="container article"><p class="answer-block"><strong>In brief:</strong> Perth Coastal Gardens helps homeowners enquire about garden rejuvenation, sandy-soil improvement, waterwise landscaping and reticulation across Perth’s northern coastal corridor. The focus is established gardens affected by fast-draining sand, dry summers, strong sun and varying coastal exposure.</p><p>Two properties in neighbouring suburbs can need very different solutions. A sheltered Joondalup courtyard may retain moisture and support a wider planting palette, while a west-facing Mullaloo frontage may experience salt-laden wind, intense afternoon heat and rapid drying. Useful advice begins with the conditions around the home rather than the suburb name alone.</p></div></section>
    <section class="section white"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Northern coastal service area</p><h2>Suburbs welcomed for garden project enquiries</h2><p>The focused service area keeps the website relevant to Perth coastal landscaping conditions. Enquiries may cover a complete garden makeover, an ageing front garden, exposed sandy beds, patchy lawn, waterwise planting, mulch, soil preparation or an irrigation system that no longer matches the layout.</p><p>Coverage ultimately depends on the selected contractor, project size, access and travel requirements. If your suburb is nearby but not listed, include the postcode and project outline so suitability can be considered.</p><ul class="location-list">${['Mullaloo','Kallaroo','Ocean Reef','Iluka','Joondalup','Hillarys','Sorrento','Duncraig','Currambine','Kinross','Burns Beach','Mindarie','Quinns Rocks','Jindalee','North Beach','Carine','Craigie','Heathridge','Beldon','Woodvale'].map(x=>`<li>${x==='Mullaloo'?`<a href="/locations/mullaloo/">${x}</a>`:x==='Joondalup'?`<a href="/locations/joondalup/">${x}</a>`:`<span class="card" style="display:inline-block;padding:.5rem .8rem">${x}</span>`}</li>`).join('')}</ul></div><figure class="media-frame short"><img src="/assets/perth-coastal-sandscape.webp" alt="Waterwise coastal garden planting beside pale sand in northern Perth" width="1280" height="720" loading="lazy"></figure></div></section>
    <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Common local priorities</p><h2>Garden services shaped by the property</h2><p>The right combination depends on what is already present, what the household wants to keep and how the outdoor areas are used.</p></div><div class="grid three">
      ${plainCard('Established garden rejuvenation','Retain useful structure while clearing, pruning and renewing beds, lawn, mulch and planting around a more practical plan.')}
      ${plainCard('Perth sandy-soil improvement','Prepare planting and lawn areas so water and nutrients can be managed more effectively in fast-draining coastal sand.')}
      ${plainCard('Waterwise garden planning','Group compatible plants, improve soil and mulch, and match irrigation zones to exposure and actual garden use.')}
      ${plainCard('Coastal planting choices','Consider salt, wind, reflected heat, mature size and shelter before selecting plants for exposed frontages and boundaries.')}
      ${plainCard('Lawn and garden-bed renewal','Decide where lawn remains useful, where beds need reshaping and how edging and access can simplify ongoing care.')}
      ${plainCard('Reticulation review','Check whether existing coverage, zones and controls still suit the lawn, beds and new planting proposed for the property.')}
    </div></div></section>
    <section class="section"><div class="container split reverse"><figure class="media-frame"><img src="/assets/mullaloo-coastal-front-garden.webp" alt="Landscaped coastal front garden in Perth northern suburbs" width="1536" height="1024" loading="lazy"></figure><div><p class="eyebrow" style="color:#4f7462">From exposed coast to inland shelter</p><h2>Microclimate matters throughout northern Perth</h2><p>Gardens closer to the ocean may need stronger consideration of wind and salt exposure. Further inland, heat, sandy soil and water management remain important, but walls, fences, trees and neighbouring buildings can create more protected pockets.</p><p>North- and west-facing areas usually receive more intense sun, while narrow side access may alternate between shade and reflected heat. Reticulation coverage can also vary as plants mature or beds change shape. Mapping these conditions helps place resilient plants where they are most needed and reserve sheltered positions for plants requiring greater protection.</p><p>The most successful garden rejuvenation is not simply a collection of fashionable plants. It is a coordinated response to soil, exposure, space, maintenance and the way the household wants to live outdoors.</p></div></div></section>
    ${ctaBand('Is your suburb nearby?','Send the property location and project outline so coverage can be confirmed.')}${relatedSection('location')}${formSection('Ask about your suburb')}`
  },
  locationPage('mullaloo','Garden Rejuvenation Mullaloo','Mullaloo garden rejuvenation','Mullaloo gardens sit squarely within the sandy coastal conditions this site addresses. Exposed front gardens, pale sand, ageing beds and patchy lawns can all form part of a rejuvenation brief.','/assets/mullaloo-coastal-front-garden.webp','/assets/perth-coastal-sandscape.webp'),
  locationPage('joondalup','Garden Rejuvenation Joondalup','Joondalup garden rejuvenation','Joondalup and its surrounding suburbs include established gardens, newer coastal homes and a wide range of outdoor spaces. Enquiries can cover soil preparation, planting, lawn, mulch and irrigation as one coordinated project.','/assets/kings-park-inspired.webp','/assets/perth-waterwise-outdoor-living.webp'),
  {
    path: 'about/index.html', nav: 'about', title: 'About Perth Coastal Gardens',
    description: "Perth Coastal Gardens connects northern coastal homeowners with garden rejuvenation enquiries focused on sandy soil and local conditions.",
    content: `${pageHero('About','Local garden information without invented claims','Perth Coastal Gardens is an independently owned lead-generation website focused on garden rejuvenation across Perth’s northern coastal suburbs.','/assets/kings-park-inspired.webp')}
    <section class="section"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">A local focus</p><h2>Why the site begins with sand</h2><p>Perth's northern coastal gardens cannot be understood only from the plants visible above ground. Pale, fast-draining sand, water movement, wind exposure, reflected heat, existing irrigation and household maintenance expectations all affect what should happen next.</p><p>A garden may look tired because it is overgrown or dated, but the visible problem can also be the result of poor soil preparation, uneven watering or plants placed in conditions that do not suit them. Perth Coastal Gardens brings these connected issues into one practical conversation.</p><p>The focus is garden rejuvenation rather than a one-size-fits-all makeover. That may mean retaining established plants, improving selected beds, changing the lawn area, simplifying maintenance or completing the work in manageable stages.</p></div><figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Sandy soil being assessed in a northern Perth coastal garden" width="1536" height="1024" loading="lazy"></figure></div></section>
    <section class="section white"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Why this website exists</p><h2>Helping homeowners make a clearer first enquiry</h2><p>Many people know that their garden is not working, but they are unsure whether they need landscaping, regular gardening, soil improvement, reticulation work or a combination. This website explains the main options in plain language and gives homeowners one place to describe the property, priorities and desired result.</p><p>Perth Coastal Gardens is an independently owned online enquiry and information website. It does not claim to be a physical landscaping depot or showroom. Enquiries may be connected with an appropriate service provider, whose availability, qualifications, quotation process and final scope must be confirmed directly.</p><p>This structure allows the information to remain useful while the eventual contractor relationship is established. When a service provider is appointed, verified details can be added without rewriting the site around assumptions.</p></div></div></section>
    <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">What customers can expect</p><h2>Useful information, realistic conversations and no invented promises</h2></div><div class="grid three">
      ${plainCard('A local coastal perspective','Information is written around Perth sand, dry summers, coastal exposure and the needs of established northern-suburb gardens.')}
      ${plainCard('A project-led enquiry','You can describe the current condition, preferred outcome, suburb, timing and any access issues without needing to diagnose the solution yourself.')}
      ${plainCard('Options rather than pressure','A garden can often be improved in stages. The first discussion should help identify priorities rather than assume everything must be replaced.')}
      ${plainCard('Clear contractor confirmation','Availability, detailed pricing, qualifications and responsibility for specialist work should be confirmed with the provider before work begins.')}
      ${plainCard('Honest visual examples','Current images illustrate coastal conditions and design direction. They are not labelled as completed client projects.')}
      ${plainCard('Room for genuine feedback','Authentic customer comments can be added once real projects and permission exist; manufactured reviews and ratings are not used.')}
    </div></div></section>
    <section class="section"><div class="container split reverse"><figure class="media-frame"><img src="/assets/kings-park-inspired.webp" alt="Layered Western Australian planting suitable for a Perth garden" width="1536" height="1024" loading="lazy"></figure><div><p class="eyebrow" style="color:#4f7462">A garden that belongs here</p><h2>Practical can still be beautiful</h2><p>Waterwise landscaping is sometimes imagined as gravel with widely spaced plants. A thoughtful Perth garden can be much richer: layered foliage, flowering natives, shade where it is useful, screening where privacy matters and materials that complement the home.</p><p>The best result balances appearance with the realities of the property. A plant that thrives in a protected Joondalup courtyard may struggle in an exposed Mullaloo frontage. Lawn can be valuable where it is used, while low-demand planting may make more sense in narrow or difficult areas.</p><p>Good planning also considers how the garden will be maintained after installation. The aim is not a photograph that looks perfect for one week; it is an outdoor space with a realistic chance of establishing and remaining enjoyable.</p></div></div></section>
    <section class="section white"><div class="container"><div class="intro"><h2>What you will not find here</h2><p>Trust is more useful than decorative claims. Until information can be verified, the website does not publish:</p></div><ul class="check-list"><li>Invented project numbers or years in business</li><li>Fabricated testimonials, customer names or star ratings</li><li>Unverified licences, guarantees or response-time promises</li><li>Images falsely described as completed projects</li><li>Fixed prices that ignore access, scope, materials and site condition</li></ul><p>Instead, homeowners are encouraged to ask questions, obtain a site-specific quote and confirm exactly who will complete the work.</p></div></section>
    ${ctaBand('Have a garden problem to discuss?','Share enough detail for a relevant first conversation.')}${formSection('Tell us about your garden')}`
  },
  {
    path: 'faq/index.html', nav: 'faq', title: 'Perth Sandy Soil and Garden Rejuvenation FAQ',
    description: "Answers about sandy soil, garden rejuvenation, waterwise planting, reticulation and quotes across Perth's northern coastal suburbs.",
    content: `${pageHero('Frequently asked questions','Planning a garden update on Perth sand','Straight answers to common questions before requesting a project discussion.','/assets/perth-coastal-sandscape.webp')}
    <section class="section"><div class="container faq">${faqItems()}</div></section>${ctaBand('Still unsure what your garden needs?','Describe the problem rather than trying to diagnose everything first.')}${formSection('Ask about your garden')}`
  },
  {
    path: 'contact/index.html', nav: 'contact', title: 'Contact Perth Coastal Gardens',
    description: 'Request a garden rejuvenation quote for Mullaloo, Joondalup or nearby Perth northern coastal suburbs. Call 0490 008 212 or enquire online.',
    content: `${pageHero('Contact','Start with the garden you have now','Tell us the suburb, the parts that are struggling and what you would like to change.','/assets/kings-park-inspired.webp')}
    <section class="section"><div class="container form-wrap"><div><p class="eyebrow" style="color:#4f7462">Contact details</p><h2>Discuss your garden</h2><p><strong>Phone</strong><br><a href="${phoneLink}">${phone}</a></p><p><strong>Email</strong><br><a href="mailto:${email}">${email}</a></p><p>Online enquiries can be submitted at any time. Attendance and phone hours will be confirmed when a service provider responds.</p><p class="notice">Perth Coastal Gardens is an online enquiry and referral website. No physical storefront is represented.</p></div>${formCard('Garden project enquiry')}</div></section>`
  },
  {
    path: 'blog/index.html', nav: 'blog', title: 'Perth Coastal Garden Advice',
    description: "Helpful Perth garden advice about sandy soil, coastal planting, waterwise landscaping, reticulation and garden rejuvenation planning.",
    content: `${pageHero('Garden advice','Useful guidance for Perth coastal gardens','Start with the soil, exposure and the way you want to use the garden—not a generic plant list.','/assets/mullaloo-coastal-front-garden.webp')}
    <section class="section"><div class="container article"><p class="answer-block"><strong>Start here:</strong> Healthy Perth coastal gardens depend on more than plant selection. Soil preparation, water movement, mulch, exposure, irrigation and household priorities should be considered together before an established garden is cleared or replanted.</p><p>This advice hub is designed for homeowners across Mullaloo, Joondalup and Perth’s northern coastal suburbs who want to understand the choices behind garden rejuvenation. The articles provide practical background for conversations with a landscaper or garden service provider; they do not replace an assessment of the property.</p></div></section>
    <section class="section white"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Resource library</p><h2>Plan before you replace</h2><p>These in-depth guides explain common decisions for established gardens on Perth's sandy coastal plain. Begin with the problem that most closely matches your property, then follow the related service and location links for the next step.</p></div><div class="grid three">
    ${articleCard('How to improve sandy soil in a Perth garden','A practical look at organic matter, wetting, mulch and realistic expectations.','/blog/improving-sandy-soil-perth-gardens/','/assets/sandy-soil-improvement.webp')}
    ${articleCard('What affects the cost of garden rejuvenation?','Understand the site and scope factors that shape a useful quotation.','/blog/garden-rejuvenation-cost-perth/','/assets/sandy-garden-before.webp')}
    ${articleCard('Planning a waterwise coastal garden','Bring soil, plant grouping, exposure, mulch and irrigation into one plan.','/blog/waterwise-coastal-garden-perth/','/assets/kings-park-inspired.webp')}
    </div></div></section>
    <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Helpful questions to ask first</p><h2>Turn a vague garden problem into a useful project brief</h2><p>You do not need to know the technical solution before making an enquiry. A few observations can help a provider understand the starting point and determine what should be inspected.</p></div><div class="grid two">
      ${plainCard('Where does the garden struggle?','Note whether problems are concentrated in full sun, deep shade, windy frontages, low points, lawn edges or areas beyond the reach of irrigation.')}
      ${plainCard('What should remain?','Identify mature plants, shade, screening, lawn, paving or structures that still work. Rejuvenation can build around useful existing features.')}
      ${plainCard('How will the space be used?','Outdoor dining, children, pets, access, privacy and street appeal all influence layout, materials and the appropriate level of planting.')}
      ${plainCard('How much maintenance feels realistic?','Be honest about pruning, watering and seasonal care. A garden suited to the household is more likely to remain attractive after installation.')}
    </div></div></section>
    <section class="section"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Advice for sandy coastal gardens</p><h2>Five principles that connect every guide</h2><h3>1. Diagnose before replacing</h3><p>Plant decline can reflect soil, irrigation, exposure, pests, root competition or several factors together. Replacing plants without addressing the cause can repeat the loss.</p><h3>2. Prepare the root zone</h3><p>Perth sand may need suitable organic matter, soil improvement and wetting support so water and nutrients are available where roots can use them.</p><h3>3. Plan for mature growth</h3><p>Spacing plants for their eventual size reduces crowding, repeated pruning and competition. It also helps paths, windows and irrigation remain accessible.</p><h3>4. Match water to zones</h3><p>Lawn, exposed beds and sheltered planting do not necessarily belong on the same watering approach. Review irrigation when the layout changes.</p><h3>5. Design for ongoing life</h3><p>The finished garden should suit the home, budget and available maintenance—not only look appealing on installation day.</p></div><figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Improving sandy soil before planting a Perth coastal garden" width="1536" height="1024" loading="lazy"></figure></div></section>
    <section class="section white"><div class="container article"><h2>When general advice is not enough</h2><p>Seek property-specific advice before major excavation, retaining work, large-tree removal, electrical work, complex irrigation changes or choosing treatments for an unexplained plant-health problem. Access, underground services, drainage and local requirements can affect what is appropriate.</p><p>For an initial garden rejuvenation discussion, share the suburb, approximate area, photographs if available, visible problems and the result you want. You can also compare <a href="/services/">Perth coastal garden services</a>, review the <a href="/locations/">northern coastal service area</a> or read the expanded <a href="/faq/">garden rejuvenation FAQ</a>.</p></div></section>
    ${ctaBand('Need advice for your own garden?','Share the suburb, current condition and the result you have in mind.')}${formSection('Discuss your Perth garden')}`
  },
  blogPage('improving-sandy-soil-perth-gardens','How to Improve Sandy Soil in a Perth Garden','Sandy soil can be improved, but lasting results usually come from treating soil structure, water movement, mulch and planting as one system.','/assets/sandy-soil-improvement.webp',`
    <h2>Why Perth sand needs a different approach</h2><p>Much of Perth's coastal plain has deep, fast-draining sandy soil. Water and soluble nutrients may move beyond shallow roots quickly, while dry areas can become difficult to wet evenly. Adding plants without preparing the growing area can repeat the same cycle of stress and replacement.</p>
    <h2>Begin with the condition of the site</h2><p>Check whether water soaks in evenly or runs away, where sun and coastal wind are strongest, and whether existing irrigation reaches the root zone. Plant decline can have more than one cause, so soil improvement should not be treated as a single-product cure.</p>
    <h2>Organic matter and soil improvers</h2><p>Well-composted organic matter can help sandy soil retain moisture and nutrients. Suitable clay-based soil improvers may also be considered. Products and rates should be selected for the intended planting and applied according to their directions; more is not automatically better.</p>
    <h2>Wetting agents, mulch and watering</h2><p>A suitable wetting agent may help where dry soil repels water. Mulch can reduce evaporation and temperature swings, while irrigation should deliver water to the correct zone without encouraging waste. These measures work best as part of a planned improvement rather than isolated treatments.</p>
    <h2>What should happen before planting?</h2><ol><li>Identify drainage, exposure and irrigation issues.</li><li>Remove weeds and unsuitable material.</li><li>Prepare the planting zone rather than a tiny planting hole.</li><li>Incorporate suitable amendments where required.</li><li>Choose plants for the finished conditions.</li><li>Mulch and establish an appropriate watering routine.</li></ol>
    <div class="source-note"><strong>Useful source:</strong> Water Corporation provides Western Australian guidance on <a href="https://www.watercorporation.com.au/Help-and-advice/Waterwise/Garden/Improve-your-soil" rel="noopener external">improving sandy soil</a>.</div>
    <h2>When should you request an assessment?</h2><p>Consider professional input when a large area repeatedly fails, irrigation and soil issues overlap, or the project involves a broader redesign. A site assessment can help avoid spending on plants before the foundation is ready.</p>`),
  blogPage('garden-rejuvenation-cost-perth','What Affects Garden Rejuvenation Costs in Perth?','Garden rejuvenation does not have one reliable square-metre price. Access, removal, soil preparation, planting, irrigation and the amount retained all influence the scope.','/assets/sandy-garden-before.webp',`
    <h2>The existing garden is part of the quotation</h2><p>A clear, accessible site with useful plants to retain is different from an overgrown garden requiring extensive removal. Mature roots, old edging, waste volume and restricted side access can affect labour and disposal before new work begins.</p>
    <h2>Soil preparation can be the hidden foundation</h2><p>In Perth's sandy coastal suburbs, a quote that considers only visible finishes may miss the work below them. Garden beds, lawns and new planting may require different preparation, and irrigation problems can need attention before the new layout is installed.</p>
    <h2>Plants, materials and establishment</h2><p>Plant size, species, quantities, mulch, edging, lawn and feature materials all change the project total. Smaller plants can reduce the initial supply cost but take longer to establish the intended look. The right balance depends on budget, timing and maintenance expectations.</p>
    <h2>How to obtain a more useful quote</h2><ul><li>Explain what you want to retain as well as remove.</li><li>Provide clear photos and approximate dimensions.</li><li>Mention access limitations and known reticulation issues.</li><li>Separate essential work from optional features.</li><li>Say whether the project can be staged.</li></ul>
    <h2>Can garden rejuvenation be completed in stages?</h2><p>Often it can. Soil and irrigation planning should still consider the whole property so that early work does not conflict with later stages. A front garden, entertaining area or most difficult planting zone can then become a logical first phase.</p>
    <h2>Avoid unsupported price promises</h2><p>Online figures can be a rough prompt, but they cannot account for site condition, contractor scope or material choices. A property-specific discussion is the safest basis for decisions and comparison.</p>`),
  blogPage('waterwise-coastal-garden-perth','How to Plan a Waterwise Coastal Garden in Perth','A waterwise garden is a coordinated plan for soil, plants, mulch and irrigation—not a promise of a water-free landscape.','/assets/kings-park-inspired.webp',`
    <h2>Start with exposure and usable space</h2><p>Coastal wind, salt, reflected heat and full western sun can create very different growing conditions within one property. Map these areas before selecting plants, and keep practical access, outdoor living and views in the plan.</p>
    <h2>Improve the soil before reducing water</h2><p>Fast-draining sand can limit the benefit of efficient irrigation if the root zone has not been prepared. Suitable organic matter, soil improvers and mulch can help water remain available for longer. The exact approach depends on the existing site.</p>
    <h2>Group plants with compatible needs</h2><p>Hydrozoning places plants with similar water requirements together. This makes it easier to water appropriately and avoids maintaining thirsty plants and low-water plants on the same schedule.</p>
    <h2>Use Western Australian character thoughtfully</h2><p>Banksias, kangaroo paws, native grasses and silver foliage can contribute colour and texture, but no plant should be selected from appearance alone. Mature size, drainage, wind tolerance and the home's architecture matter too.</p>
    <h2>Review irrigation as the garden changes</h2><p>Old sprinkler positions may no longer match reshaped beds or maturing plants. Review coverage, leaks, zoning and controller settings, and use appropriately qualified help where work requires it.</p>
    <div class="source-note"><strong>Useful source:</strong> The Waterwise program provides local information about <a href="https://www.watercorporation.com.au/Help-and-advice/Waterwise/Garden" rel="noopener external">waterwise gardening in Western Australia</a>.</div>
    <h2>What does a good plan achieve?</h2><p>The result should suit the household as well as the climate: clear circulation, useful outdoor areas, manageable maintenance, healthier planting and a watering approach matched to each zone.</p>`),
  {
    path: 'privacy/index.html', nav: '', title: 'Privacy Policy Perth Coastal Gardens',
    description: 'Privacy information for Perth Coastal Gardens enquiries, referrals and website analytics.',
    content: `${simpleHero('Privacy policy','How enquiry information is collected and used.')}
    <section class="section white"><div class="container" style="max-width:850px"><h2>Information collected</h2><p>When you submit an enquiry, this website may collect your name, email, phone number, suburb, service interest and project message. Basic website usage information may also be collected through analytics and security services.</p><h2>Why it is collected</h2><p>Information is used to respond to your request, assess whether the enquiry matches the service area and refer the request to a suitable service provider where appropriate.</p><h2>Enquiry referrals</h2><p>By submitting a service enquiry, you understand that relevant details may be shared with a service provider so that they can contact you about the requested work. Information is not sold as a general marketing list.</p><h2>Email and forms</h2><p>Messages may be processed by email-forwarding and form-delivery providers. Do not send highly sensitive personal information through the website.</p><h2>Your choices</h2><p>You may ask about the information associated with your enquiry or request correction or deletion where applicable by emailing <a href="mailto:${email}">${email}</a>.</p><h2>General information</h2><p>Garden information on this website is general. A site-specific assessment is required before choosing treatments, materials or planting.</p></div></section>`
  },
  legalPage('terms','Terms of Use','These terms explain the role of Perth Coastal Gardens as an online enquiry and referral website.',`<h2>Website role</h2><p>Perth Coastal Gardens publishes general garden information and receives service enquiries. It does not represent a physical storefront or guarantee that a particular contractor will be available.</p><h2>Quotes and agreements</h2><p>Any inspection, scope, price, timing, warranty or service agreement must be confirmed directly with the service provider. Submitting an enquiry does not create a contract for work.</p><h2>Information accuracy</h2><p>Reasonable care is taken with website content, but garden conditions vary. Information may be updated and should not replace property-specific advice.</p><h2>Acceptable use</h2><p>Do not misuse the forms, attempt to interfere with the website, or submit unlawful or misleading material.</p><h2>Contact</h2><p>Questions about these terms may be emailed to <a href="mailto:${email}">${email}</a>.</p>`),
  legalPage('disclaimer','Website Disclaimer','Important limits applying to garden information, images and service enquiries.',`<h2>General information only</h2><p>Content is educational and general. Soil, drainage, irrigation, plants and site conditions should be assessed before work or purchasing decisions.</p><h2>Illustrative images</h2><p>Current photographs illustrate local conditions and design ideas. They are not represented as projects completed by Perth Coastal Gardens or a future service provider.</p><h2>No unsupported promises</h2><p>This website does not promise a particular result, response time, price, licence status, warranty or availability. Contractor-specific claims will be published only after verification.</p><h2>External sources</h2><p>Links to external information are provided for convenience. Their owners control and may update that content.</p>`),
  {
    path: 'thank-you/index.html', nav: '', title: 'Thank You Perth Coastal Gardens', noindex: true,
    description: 'Your Perth Coastal Gardens enquiry has been submitted.',
    content: `${simpleHero('Thank you','Your enquiry has been submitted. Please keep a copy of any photographs or project details you may wish to discuss.')}
    <section class="section"><div class="container" style="text-align:center"><a class="button" href="/">Return home</a></div></section>`
  },
  {
    path: '404.html', nav: '', title: 'Page Not Found Perth Coastal Gardens', noindex: true,
    description: 'The requested page could not be found.',
    content: `${simpleHero('Page not found','The address may have changed or the page may no longer be available.')}
    <section class="section"><div class="container" style="text-align:center"><a class="button" href="/">Return home</a></div></section>`
  }
];

function serviceCard(title, text, href) { return `<article class="card"><h3>${title}</h3><p>${text}</p><a class="text-link" href="${href}">Learn more</a></article>`; }
function articleCard(title,text,href,image) { return `<article class="article-card"><a href="${href}" aria-label="Read ${title}"><img src="${image}" alt="${title}" width="1536" height="1024" loading="lazy"></a><div><p class="eyebrow" style="color:#4f7462">Garden guide</p><h3><a href="${href}">${title}</a></h3><p>${text}</p><a class="text-link" href="${href}">Read the guide</a></div></article>`; }
function plainCard(title, text) { return `<article class="card"><h3>${title}</h3><p>${text}</p></article>`; }
function ctaBand(title, text) { return `<section class="band"><div class="container band-inner"><div><h2>${title}</h2><p>${text}</p></div><div class="cta-actions"><a class="button" href="/contact/">Request a quote</a><a class="button secondary" style="border-color:white;color:white!important" href="${phoneLink}">Call ${phone}</a></div></div></section>`; }
function pageHero(label, title, text, image) { return `<section class="page-hero has-image" style="--page-image:url('${image}')"><div class="container"><div class="crumbs"><a href="/">Home</a> / ${label}</div><p class="eyebrow">Perth Coastal Gardens</p><h1>${title}</h1><p>${text}</p><div class="hero-actions"><a class="button sand" href="/contact/">Request a quote</a><a class="button secondary" href="${phoneLink}">Call ${phone}</a></div></div></section>`; }
function simpleHero(title,text) { return `<section class="page-hero"><div class="container"><h1>${title}</h1><p>${text}</p></div></section>`; }
function formCard(subject) { return `<div class="form-card"><form action="https://formsubmit.co/${email}" method="POST"><input type="hidden" name="_subject" value="${subject} from perthcoastgardens.com"><input type="hidden" name="_next" value="${domain}/thank-you/"><input type="text" name="_honey" class="form-honey" tabindex="-1" autocomplete="off"><label>Name<input name="name" type="text" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Phone<input name="phone" type="tel" autocomplete="tel" required></label><label>Suburb or postcode<input name="suburb" type="text" autocomplete="postal-code" required></label><label class="full">Service needed<select name="service" required><option value="">Choose one</option><option>Garden rejuvenation</option><option>Sandy-soil improvement</option><option>Waterwise landscaping</option><option>Reticulation assessment</option><option>Lawn or garden-bed renewal</option><option>Unsure</option></select></label><label class="full">Message<textarea name="message" required placeholder="What is struggling, what would you like to change, and when are you hoping to begin?"></textarea></label><p class="form-note">By submitting this form, you agree that your enquiry may be shared with a suitable service provider so they can contact you about the requested work. See the <a href="/privacy/">privacy policy</a>.</p><button type="submit">Send garden enquiry</button></form></div>`; }
function formSection(title) { return `<section class="section" id="quote"><div class="container form-wrap"><div><p class="eyebrow" style="color:#4f7462">Your garden and location</p><h2>${title}</h2><p>Share the suburb, visible problems and the result you would like. Photos can be discussed after the initial enquiry.</p><p><strong>Prefer to call?</strong><br><a href="${phoneLink}">${phone}</a></p></div>${formCard(title)}</div></section>`; }
function relatedSection(context='service') { return `<section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Continue planning</p><h2>Related local garden information</h2><p>Follow the subject that best matches your property, then use the enquiry page when you are ready to discuss the site.</p></div><nav class="related-grid" aria-label="Related garden information">
  ${context!=='service'?'<a href="/services/garden-rejuvenation/"><strong>Garden rejuvenation</strong><span>Plan a coordinated update</span></a>':''}
  <a href="/services/sandy-soil-improvement/"><strong>Sandy-soil improvement</strong><span>Prepare the growing foundation</span></a>
  <a href="/services/waterwise-landscaping/"><strong>Waterwise landscaping</strong><span>Plan planting and watering together</span></a>
  <a href="/locations/mullaloo/"><strong>Garden rejuvenation in Mullaloo</strong><span>Local coastal garden context</span></a>
  <a href="/locations/joondalup/"><strong>Garden rejuvenation in Joondalup</strong><span>Services across the Joondalup area</span></a>
  <a href="/blog/"><strong>Perth coastal garden advice</strong><span>Read practical planning guides</span></a>
</nav></div></section>`; }
function getServiceDetails(slug) { return ({
  'garden-rejuvenation': {
    heading: 'Rework what is tired while keeping what still belongs',
    paragraphs: [
      'Garden rejuvenation sits between routine maintenance and a complete landscape rebuild. It is useful when the basic space still has value but the planting has become overgrown, beds have lost definition, lawn is failing or the garden no longer suits the household. The first task is to separate assets from problems: mature plants may provide shade or structure, while others may be poorly positioned, unhealthy or creating too much maintenance.',
      'A coordinated rejuvenation can include selective clearing, pruning, reshaping beds, improving soil, renewing mulch, introducing new planting and reviewing lawn or irrigation. Front gardens may focus on street appeal and a welcoming entrance; back gardens may prioritise usable space, screening, shade and easier care. Narrow side areas can be simplified so they remain tidy and accessible.',
      'The work does not have to happen at once. A staged plan might begin with clearing and soil preparation, then move to irrigation, planting and finishing. This can protect the budget while ensuring that early work supports later stages instead of being removed or repeated.'
    ]
  },
  'sandy-soil-improvement': {
    heading: 'Improve the growing foundation before replacing plants',
    paragraphs: [
      'Much of Perth sits on deep sandy soil that can drain rapidly and hold limited moisture and nutrients. Some areas also become difficult to wet evenly after drying. This means a plant may receive frequent watering but still have an inconsistent root-zone environment. Simply adding fertiliser or installing new plants may provide only a temporary improvement if the underlying soil and water movement are ignored.',
      'A site-specific approach can consider well-composted organic matter, suitable soil improvers, wetting products, mulch and irrigation delivery. The right combination depends on whether the area is lawn, an established bed, a new planting zone or a container garden. Existing roots, drainage, product instructions and the intended plants also matter; adding more of a product is not automatically better.',
      'Soil improvement is usually most efficient before major planting, but established beds can often be improved carefully over time. The goal is a more reliable growing environment—not to turn Perth sand into heavy soil or promise that watering and maintenance will no longer be needed.'
    ]
  },
  'waterwise-landscaping': {
    heading: 'Use water more thoughtfully without creating a bare garden',
    paragraphs: [
      'Waterwise landscaping brings several decisions together: soil condition, plant grouping, mulch, shade, wind exposure and irrigation. It is not a particular visual style and it does not require every lawn or lush plant to be removed. A family may keep lawn where it is genuinely used, create fuller planting near outdoor living areas and simplify difficult verges or boundaries.',
      'The planting palette should respond to the microclimate rather than relying on one list for the entire property. Tougher coastal or Western Australian species may suit exposed positions, while sheltered courtyards can support plants needing greater protection. Mature size is as important as appearance at purchase; allowing appropriate space can reduce crowding, repeated pruning and competition at the root zone.',
      'Good mulch and prepared soil can reduce evaporation and help moderate root-zone temperature. Irrigation should then match the zones rather than applying the same schedule everywhere. The finished plan should reflect the owner’s appetite for gardening, because even a waterwise landscape needs establishment care, seasonal attention and occasional adjustment.'
    ]
  },
  'reticulation-upgrades': {
    heading: 'Match watering zones to the garden that exists now',
    paragraphs: [
      'Reticulation systems often outlive the garden layout they were designed for. Beds expand, lawn is reduced, plants mature and sprinkler patterns become blocked or misaligned. The result can be dry patches beside overwatered areas, water landing on paving or a controller schedule that no longer reflects what each zone needs.',
      'An assessment can look for visible leaks, damaged heads, poor coverage, unsuitable nozzles, mixed plant requirements and controls that are difficult to manage. If the garden is being rejuvenated, irrigation planning should happen before final planting and mulch so new work is not disturbed unnecessarily. Lawn, garden beds and containers may need different delivery methods or schedules.',
      'Not every issue requires a complete replacement. Adjustments, repairs or rezoning may be enough, while older or heavily altered systems may need broader work. Any specialist or regulated component should be handled by an appropriately capable provider, and the final watering settings should follow current local requirements and seasonal conditions.'
    ]
  }
})[slug]; }
function servicePage(slug,title,label,lead,issues,body,image) { const detail=getServiceDetails(slug); return { path:`services/${slug}/index.html`, nav:'services', title, description:`${label} for sandy coastal gardens across Mullaloo, Joondalup and Perth's northern suburbs. Request a project discussion and quote.`, content:`${pageHero('Services',label,lead,image)}<section class="section"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">When this may help</p><h2>Start with what is happening now</h2><ul class="check-list">${issues.map(x=>`<li>${x}</li>`).join('')}</ul><p>${body}</p><p>For broader planning, compare all <a href="/services/">Perth coastal garden services</a> or read the guide to <a href="/blog/improving-sandy-soil-perth-gardens/">improving sandy soil before planting</a>.</p></div><figure class="media-frame"><img src="${image}" alt="${label} in a sandy northern coastal Perth garden" width="1536" height="1024" loading="lazy"></figure></div></section>
  <section class="section white"><div class="container article"><p class="eyebrow" style="color:#4f7462">A considered approach</p><h2>${detail.heading}</h2>${detail.paragraphs.map(x=>`<p>${x}</p>`).join('')}<h3>What helps create an accurate quote?</h3><p>Include the suburb, approximate size of the area, access limitations, current problems, features you hope to retain and the result you want. Photographs can help explain the starting point, but a site visit may still be required before materials, quantities, plant choices or specialist work can be confirmed.</p></div></section>
  <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">What customers can expect</p><h2>A practical discussion before the scope is finalised</h2><p>The provider should consider the property rather than treating every coastal garden as identical.</p></div><div class="grid three">${plainCard('Existing conditions considered','Soil, exposure, access, irrigation and useful existing plants should inform the recommendation.')}${plainCard('Priorities made clear','The quotation conversation should distinguish essential preparation from optional finishing work and future stages.')}${plainCard('No automatic total removal','Where plants, structures or lawn areas remain useful, retaining them may be more sensible than starting again.')}${plainCard('Maintenance discussed','Planting and materials should suit the time and effort the household realistically wants to provide.')}${plainCard('Specialist work identified','Electrical, plumbing, tree or other specialist requirements should be recognised and appropriately handled.')}${plainCard('A defined quotation','The agreed scope, major inclusions and relevant exclusions should be clear before work proceeds.')}</div></div></section>
  ${ctaBand('Discuss the next step for your garden','A useful quote begins with the property, scope and current condition.')}${relatedSection('service')}${formSection(`Request a ${label.toLowerCase()} quote`)}`}; }
function getLocationDetails(slug) { return ({
  mullaloo: {
    summary: 'Mullaloo garden projects often need to balance coastal exposure with attractive street presentation and practical outdoor living. Properties closer to the ocean may experience stronger wind and salt, while sheltered pockets around walls and courtyards can support a wider range of planting.',
    heading: 'Planning for exposed Mullaloo garden conditions',
    paragraphs: [
      'Mullaloo’s coastal position makes microclimate particularly important. A front garden facing afternoon sun and ocean winds may dry quickly and need resilient structural planting, careful soil preparation and dependable mulch. A protected rear courtyard at the same property can behave quite differently, especially where fences, buildings or mature trees provide shelter.',
      'Established homes may have garden beds and reticulation that have been altered several times. Sprinklers can become blocked by mature plants, lawn may have receded from shaded areas and individual replacements can leave the design visually disconnected. Garden rejuvenation offers an opportunity to review these issues together rather than treating each symptom separately.',
      'A useful Mullaloo garden plan can retain healthy screening and mature structure while simplifying high-maintenance areas. Coastal-tolerant planting, improved sandy soil, appropriate irrigation zones and purposeful lawn can create a garden that feels full without relying on plants poorly matched to the exposure.'
    ],
    priorities: ['Wind and salt exposure around frontages and boundaries','Fast-draining sandy beds that dry unevenly','Screening and privacy without excessive crowding','Reticulation coverage after gardens have matured','Street appeal suited to the home and coastal setting','Planting that matches realistic maintenance']
  },
  joondalup: {
    summary: 'Joondalup garden rejuvenation can cover established suburban gardens, newer outdoor areas and mixed conditions ranging from exposed sunny frontages to protected courtyards. Soil, irrigation and the household’s use of the space should shape the scope.',
    heading: 'Coordinating soil, planting and outdoor use in Joondalup',
    paragraphs: [
      'Joondalup properties can contain several distinct garden zones: a formal or waterwise front garden, lawn or entertaining space at the rear, narrow side access and sheltered planting near the home. Each zone receives different sun, wind and water, so using one plant palette or irrigation schedule across the whole property may produce uneven results.',
      'Older gardens may have valuable mature plants but tired underplanting, compacted or depleted beds and an irrigation layout that no longer matches the landscape. Newer homes can face the opposite challenge—limited shade, exposed sand and outdoor areas that need structure. Both situations benefit from defining what should remain before choosing new plants or materials.',
      'A coordinated Joondalup garden update might combine selective clearing, sandy-soil preparation, reshaped beds, screening, lawn decisions, mulch and reticulation adjustments. The goal is an outdoor space that complements the home and remains manageable after the initial installation period.'
    ],
    priorities: ['Established beds needing renewal rather than total removal','Sandy-soil preparation before new lawn or planting','Shade, screening and privacy around outdoor living areas','Waterwise planting grouped around suitable zones','Simpler access and lower-maintenance side areas','Reticulation adjustments for a changed garden layout']
  }
})[slug]; }
function locationPage(slug,title,label,text,heroImage='/assets/sandy-garden-before.webp',bodyImage='/assets/perth-coastal-garden-hero.webp') { const place=label.replace(' garden rejuvenation',''); const detail=getLocationDetails(slug); return { path:`locations/${slug}/index.html`, nav:'locations', title, description:`${label} enquiries for sandy soil improvement, waterwise planting and established garden updates in Perth's northern coastal suburbs.`, content:`${pageHero('Locations',label,text,heroImage)}
  <section class="section"><div class="container article"><p class="answer-block"><strong>Local overview:</strong> ${detail.summary}</p></div></section>
  <section class="section white"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Local garden rejuvenation</p><h2>Garden updates suited to ${place}</h2><p>${text}</p><p>Homeowners can enquire about:</p><ul class="check-list"><li><a href="/services/garden-rejuvenation/">Complete garden rejuvenation</a></li><li><a href="/services/sandy-soil-improvement/">Sandy-soil and garden-bed improvement</a></li><li><a href="/services/waterwise-landscaping/">Waterwise and coastal planting</a></li><li><a href="/services/reticulation-upgrades/">Lawn and reticulation considerations</a></li></ul><p>Availability and the final scope must be confirmed for the property and selected service provider. See the <a href="/locations/">full northern coastal service area</a> or read <a href="/blog/garden-rejuvenation-cost-perth/">what affects a garden rejuvenation quote</a>.</p></div><figure class="media-frame"><img src="${bodyImage}" alt="Waterwise coastal garden suited to a ${place} area home" width="1536" height="1024" loading="lazy"></figure></div></section>
  <section class="section"><div class="container article"><p class="eyebrow" style="color:#4f7462">Property-specific planning</p><h2>${detail.heading}</h2>${detail.paragraphs.map(x=>`<p>${x}</p>`).join('')}</div></section>
  <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Common priorities</p><h2>What may be considered during a ${place} garden assessment</h2><p>The final recommendation should respond to the actual property rather than a generic suburb-wide formula.</p></div><div class="grid two">${detail.priorities.map(x=>plainCard(x,'Discuss the existing condition, desired result and whether this item should be addressed now or planned as a later stage.')).join('')}</div></div></section>
  <section class="section white"><div class="container article"><h2>Preparing a useful garden enquiry</h2><p>Include the ${place} property location, approximate area, visible problems, preferred outcome and any timing or access limitations. Mention plants, lawn, structures or screening you hope to retain. Photographs can help explain the starting point, but a site visit may still be needed before quantities, materials, plant selections and specialist work are confirmed.</p><p>You do not need to diagnose the problem yourself. Descriptions such as “water runs through the bed,” “the lawn stays patchy,” “plants burn near the front wall” or “the garden has become too difficult to maintain” provide a practical starting point.</p></div></section>
  ${ctaBand(`Planning a garden update in ${place}?`,'Send the project outline and property location for a relevant discussion.')}${relatedSection('location')}${formSection(`Request a quote in ${place}`)}`}; }
function blogPage(slug,title,answer,image,body) { return {path:`blog/${slug}/index.html`,nav:'blog',title,description:answer,article:true,content:`${pageHero('Garden advice',title,answer,image)}<article class="section white"><div class="container article"><p class="article-meta">Perth Coastal Gardens · General garden guidance · Updated September 2026</p><p class="answer-block"><strong>In brief:</strong> ${answer}</p>${body}<aside class="article-cta"><h2>Discuss your own garden</h2><p>General guidance is a starting point. Explore <a href="/services/">garden rejuvenation services</a>, check the <a href="/locations/">northern coastal service area</a>, or share your suburb and current garden condition.</p><a class="button" href="/contact/">Request a discussion</a></aside></div></article>${relatedSection('article')}${formSection('Request a garden project quote')}`}; }
function legalPage(slug,title,intro,body) { return {path:`${slug}/index.html`,nav:'',title:`${title} Perth Coastal Gardens`,description:intro,content:`${simpleHero(title,intro)}<section class="section white"><div class="container article">${body}</div></section>`}; }
function faqItems() { const items=[
  ['Why do gardens struggle in Perth sand?','Much of Perth’s coastal plain has sandy ground that can drain rapidly and hold limited moisture and nutrients. Once very dry, some areas may also wet unevenly, so water can bypass parts of the root zone. Strong sun, reflected heat, coastal wind, plant selection and irrigation coverage can add to the stress. The useful question is therefore not only how often the garden is watered, but whether the soil, mulch, watering method and plants are working together. A site assessment helps separate soil problems from shade, pests, root competition, damaged irrigation or other causes.'],
  ['Can sandy soil be improved?','Often, yes, although improvement is normally an ongoing process rather than a single treatment. Depending on the area and intended planting, options may include well-composted organic matter, suitable soil improvers, wetting products, mulch and changes to irrigation. Lawn, established beds and new planting zones may need different treatment. Products should be chosen and applied for the actual site, because excessive or unsuitable additions can create new problems. The aim is to improve moisture and nutrient management while retaining the free-draining qualities that many plants need.'],
  ['What is garden rejuvenation?','Garden rejuvenation refreshes an existing outdoor area without assuming that everything must be demolished. It can include selective clearing, pruning, reshaping beds, soil preparation, lawn work, new planting, mulch and a review of irrigation. The scope may be visual, practical or both—for example, improving street appeal while reducing maintenance, or retaining mature screening while replacing plants that repeatedly fail. It is especially useful where the garden has good bones but has become dated, overgrown, patchy or poorly matched to the way the household now uses the space.'],
  ['Is rejuvenation different from regular gardening?','Yes. Regular gardening generally maintains the existing arrangement through mowing, pruning, weeding and seasonal care. Rejuvenation steps back and asks whether the layout, soil, planting and watering still make sense. It may involve one-off improvement work and a coordinated plan rather than recurring maintenance alone. After the rejuvenation is established, ongoing gardening will still be needed, but it should support a garden that is better suited to the property and household. If the existing design already works and only needs care, regular maintenance may be the more appropriate service.'],
  ['What makes a garden waterwise?','A waterwise garden uses water thoughtfully through a combination of healthy soil, suitable plants, mulch, sensible grouping and efficient irrigation. It does not have to be bare, entirely native, water-free or maintenance-free. Lawn can be retained where it serves a purpose, while difficult or unused areas may be converted to lower-demand planting. Plants with similar needs are easier to water as a zone, and shade or shelter can reduce stress in selected areas. Establishment watering is still important, and seasonal adjustments may be needed as plants mature.'],
  ['Which plants suit coastal gardens?','Suitability depends on more than distance from the ocean. Consider direct salt exposure, wind strength, summer sun, reflected heat, drainage, mature plant size, irrigation and the level of maintenance available. Tough Western Australian species can be excellent choices, but not every native suits every position. Sheltered courtyards may support plants that would struggle in an exposed frontage. A layered mix of structural plants, flowering species and groundcovers can create fullness while protecting the soil. Final selections should follow the conditions of the particular bed rather than a generic coastal plant list.'],
  ['Can only part of the garden be updated?','Yes. Staging can be a sensible way to control cost and disruption. A project might begin with the front garden, one difficult bed, a patchy lawn area, an exposed verge or an irrigation problem. Where several stages are planned, it helps to consider the final direction before the first work begins. This reduces the chance that new edging, pipes or planting will need to be moved later. Soil and watering problems are often worth addressing early because they affect the success of later planting and finishing work.'],
  ['Do all existing plants need to be removed?','Not necessarily. Mature plants can provide shade, privacy, habitat and structure that would take years to replace. A useful assessment identifies which plants are healthy and appropriately placed, which may respond to pruning or improved conditions, and which are unsuitable, failing or creating excessive maintenance. Retaining selected plants can also preserve character and reduce waste. Removal may still be appropriate where plants are unsafe, invasive, badly positioned or incompatible with the intended use of the garden. Tree work requiring specialist skills should be referred appropriately.'],
  ['How much does a garden makeover cost?','Cost varies with the area, access, clearing and disposal, soil preparation, irrigation, lawn, plant sizes, mulch, edging, paving or other construction. A small targeted renewal may be very different from a full front-and-back garden transformation. Existing services, difficult access and the need for specialist trades can also affect the quote. The most useful approach is to identify priorities and obtain a site-specific scope. If the complete wish list exceeds the available budget, ask whether the project can be staged without compromising the early work.'],
  ['How long does garden rejuvenation take?','Timing depends on the size and complexity of the work, access, material and plant availability, weather and whether specialist trades are involved. A focused bed renewal may be completed comparatively quickly, while clearing, soil improvement, irrigation changes, lawn preparation and planting across a whole property require more coordination. Newly installed gardens also need an establishment period after the physical work is finished. When requesting a quote, mention any important event or deadline, but allow the provider to confirm whether it is realistic for the proposed scope.'],
  ['Do you service my suburb?','The initial focus is Mullaloo, Joondalup and nearby northern coastal suburbs including Ocean Reef, Kallaroo, Iluka, Hillarys, Sorrento, Duncraig, Currambine, Burns Beach, Mindarie and surrounding areas. Exact coverage depends on the selected provider, project size and travel requirements. If your suburb is nearby but not named, submit the postcode and a short project description. Larger or particularly suitable projects may have a different practical service radius from small maintenance-style requests.'],
  ['What information should I include in an enquiry?','Provide the suburb, approximate area, what is currently going wrong, the result you want and your preferred timing. Mention access restrictions, pets, slopes, retained trees or structures, existing irrigation and whether the work could be staged. Photographs can help show the condition and scale, although they do not replace a site visit where one is needed. You do not need to diagnose the garden yourself; describing symptoms such as patchy lawn, exposed sand, dying plants or uneven watering is a useful starting point.'],
  ['Are quotes free?','The quoting policy depends on the service provider and the level of work required to prepare the proposal. A straightforward site visit and estimate may be offered without charge, while detailed design, planting plans, measurements or specialist assessment may involve a fee. Ask what is included before arranging the visit and whether any design fee is credited toward the project if work proceeds. Perth Coastal Gardens does not promise a free quotation on behalf of a future contractor whose policies have not yet been confirmed.'],
  ['Are the photographs completed projects?','No. The current photographs illustrate Perth coastal conditions, sandy soil, planting ideas and possible design directions. They are not presented as completed client projects or evidence of a particular contractor’s work. This distinction matters because genuine portfolios and testimonials should be based on real projects and used with permission. Once a service provider has verified material available, authentic project images and customer feedback can be added and clearly identified. Until then, the images are inspiration and context rather than a claimed portfolio.']
]; return items.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join(''); }

function header(current) {
  const link=(key,href,label)=>`<a href="${href}" ${current===key?'aria-current="page"':''}>${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"></span><span>Perth Coastal Gardens</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav class="nav" id="site-nav" aria-label="Primary">${link('home','/','Home')}${link('services','/services/','Services')}${link('locations','/locations/','Locations')}${link('blog','/blog/','Advice')}${link('about','/about/','About')}${link('faq','/faq/','FAQ')}${link('contact','/contact/','Contact')}<a class="button header-call" href="${phoneLink}">${phone}</a></nav></div></header>`;
}
function footer() { return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><h2>Perth Coastal Gardens</h2><p>Garden rejuvenation enquiries for sandy soils across Perth's northern coastal suburbs.</p><p><a href="${phoneLink}">${phone}</a><br><a href="mailto:${email}">${email}</a></p></div><div><h3>Explore</h3><ul><li><a href="/services/">Garden services</a></li><li><a href="/locations/">Service areas</a></li><li><a href="/blog/">Garden advice</a></li><li><a href="/faq/">Frequently asked questions</a></li></ul></div><div><h3>Information</h3><ul><li><a href="/about/">About this website</a></li><li><a href="/contact/">Contact</a></li><li><a href="/privacy/">Privacy policy</a></li><li><a href="/terms/">Terms of use</a></li><li><a href="/disclaimer/">Disclaimer</a></li></ul></div></div><div class="legal"><span>© <span data-year></span> Perth Coastal Gardens</span><span>Online enquiry and referral website. No physical storefront represented.</span></div></div></footer>`; }
function schema(page,url) { const graph=[{'@type':'WebSite','@id':`${domain}/#website`,url:domain,name:'Perth Coastal Gardens',inLanguage:'en-AU',description:'Garden rejuvenation information and enquiries for Perth northern coastal suburbs'},{'@type':'Organization','@id':`${domain}/#organization`,name:'Perth Coastal Gardens',url:domain,email,telephone:'+61490008212',areaServed:['Mullaloo','Joondalup','Perth northern coastal suburbs']},{'@type':page.article?'Article':'WebPage','@id':`${url}#webpage`,url,name:page.title,isPartOf:{'@id':`${domain}/#website`},description:page.description,inLanguage:'en-AU',...(page.article?{author:{'@id':`${domain}/#organization`},publisher:{'@id':`${domain}/#organization`},dateModified:'2026-09-14'}:{})}]; return JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c'); }
function shell(page) { const clean=page.path==='index.html'?'':page.path.replace(/index\.html$/,''); const url=`${domain}/${clean}`; const title=`${page.title} | Perth Coastal Gardens`; const machineLinks=page.path==='index.html'?'<link rel="alternate" type="text/markdown" href="/index.md" title="Markdown version of this homepage"><link rel="describedby" type="text/plain" href="/llms.txt">':''; return `<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${page.description}">${page.noindex?'<meta name="robots" content="noindex,follow">':''}<link rel="canonical" href="${url}">${machineLinks}<meta property="og:type" content="${page.article?'article':'website'}"><meta property="og:locale" content="en_AU"><meta property="og:site_name" content="Perth Coastal Gardens"><meta property="og:title" content="${title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${page.description}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${schema(page,url)}</script></head><body>${header(page.nav)}<main id="main">${page.content}</main>${footer()}<script src="/app.js" defer></script></body></html>`; }

await rm('dist',{recursive:true,force:true});
await mkdir('dist/assets',{recursive:true});
for (const image of ['perth-coastal-garden-hero.webp','sandy-garden-before.webp','sandy-soil-improvement.webp','kings-park-inspired.webp','mullaloo-coastal-front-garden.webp','perth-coastal-sandscape.webp','perth-reticulation-garden.webp','perth-waterwise-outdoor-living.webp']) {
  await cp(join('src/assets', image), join('dist/assets', image));
}
await cp('src/styles.css','dist/styles.css');
await cp('src/app.js','dist/app.js');
for (const page of pages) { const out=join('dist',page.path); await mkdir(dirname(out),{recursive:true}); await writeFile(out,shell(page)); }
const urls=pages.filter(p=>!p.noindex&&p.path!=='404.html').map(p=>`${domain}/${p.path==='index.html'?'':p.path.replace(/index\.html$/,'')}`);
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/index.md',`# Perth Coastal Gardens\n\n> Garden rejuvenation information and project enquiries for Perth's northern coastal suburbs.\n\n## What this website covers\n\nPerth Coastal Gardens focuses on established gardens affected by fast-draining sandy soil, coastal exposure, dry summers and changing household needs. It provides practical information and an enquiry pathway rather than representing a physical storefront.\n\n## Services\n\n- [Garden rejuvenation](${domain}/services/garden-rejuvenation/)\n- [Sandy-soil improvement](${domain}/services/sandy-soil-improvement/)\n- [Waterwise landscaping](${domain}/services/waterwise-landscaping/)\n- [Reticulation assessment and upgrades](${domain}/services/reticulation-upgrades/)\n\n## Service area\n\nMullaloo, Joondalup and nearby northern coastal suburbs of Perth, Western Australia. Coverage and provider availability must be confirmed for each property.\n\n## Useful resources\n\n- [All garden services](${domain}/services/)\n- [Northern coastal service area](${domain}/locations/)\n- [Perth coastal garden advice](${domain}/blog/)\n- [Frequently asked questions](${domain}/faq/)\n- [Contact Perth Coastal Gardens](${domain}/contact/)\n\n## Accuracy\n\nCurrent photographs illustrate local conditions and design ideas rather than completed client projects. This Markdown version does not imply unverified testimonials, ratings, years in business, qualifications, guarantees, response times or project totals. Contractor-specific details must be confirmed directly.\n\n## Contact\n\n- Phone: ${phone}\n- Email: ${email}\n`);
await writeFile('dist/_headers',`/*\n  Vary: Accept\n\n/\n  Link: </index.md>; rel="alternate"; type="text/markdown", </llms.txt>; rel="describedby"\n\n/index.md\n  Content-Type: text/markdown; charset=utf-8\n  X-Markdown-Tokens: 310\n  X-Robots-Tag: noindex\n  Vary: Accept\n  X-AEO-Version: 1.0\n\n/llms.txt\n  Content-Type: text/plain; charset=utf-8\n  X-Robots-Tag: noindex\n`);
await writeFile('dist/llms.txt',`# Perth Coastal Gardens\n\n> Garden rejuvenation information and enquiry website for Perth's northern coastal suburbs.\n\n## Core topics\n- Garden rejuvenation on sandy coastal soils\n- Sandy-soil improvement\n- Waterwise landscaping\n- Reticulation assessment and upgrades\n\n## Service area\nMullaloo, Joondalup and nearby northern coastal suburbs of Perth, Western Australia.\n\n## Key pages\n- ${domain}/services/\n- ${domain}/locations/\n- ${domain}/blog/\n- ${domain}/faq/\n- ${domain}/contact/\n\n## Contact\n- Phone: ${phone}\n- Email: ${email}\n\nImages illustrate local conditions and design ideas and are not represented as completed client projects. Contractor-specific claims must be confirmed directly.\n\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/llms-full.txt',`# Perth Coastal Gardens — detailed site guide\n\nPerth Coastal Gardens is an independently owned online lead-generation and garden-information website. It helps homeowners describe garden rejuvenation projects and request contact from a suitable service provider. It does not represent a physical storefront.\n\nThe editorial focus is the relationship between Perth's sandy coastal soils, water movement, planting, mulch, lawn and reticulation. Core service information covers complete garden rejuvenation, sandy-soil improvement, waterwise landscaping and reticulation assessment. Location information focuses on Mullaloo, Joondalup and the connected northern coastal corridor.\n\nThe Garden Advice library contains general educational guides. Property-specific assessment is required before selecting treatments, materials or plants. Current images are illustrative rather than portfolio evidence. No ratings, reviews, project totals, years in business, licence claims, response times or guarantees should be inferred unless later published with verification.\n\nAuthoritative navigation: ${domain}/services/ | ${domain}/locations/ | ${domain}/blog/ | ${domain}/faq/ | ${domain}/contact/\nContact: ${phone} | ${email}\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/_redirects',`https://www.perthcoastgardens.com/* https://perthcoastgardens.com/:splat 301\n`);
await writeFile('dist/favicon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#173642"/><path d="M12 38c12-4 18-15 25-24 7 14 15 21 15 31-7-7-15-10-24-9 7 3 13 8 17 15-14 1-25-3-33-13Z" fill="#4F7462"/><path d="M15 44c12-7 24-9 36-5" fill="none" stroke="#D9C7A3" stroke-width="5" stroke-linecap="round"/></svg>`);
console.log(`Built ${pages.length} pages`);
