import { mkdir, rm, cp, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const domain = 'https://perthcoastgardens.com';
const phone = '0490 008 212';
const phoneLink = 'tel:+61490008212';
const email = 'info@perthcoastgardens.com';

const pages = [
  {
    path: 'index.html', nav: 'home', title: 'Garden Rejuvenation Perth Northern Suburbs',
    description: "Garden rejuvenation for Perth's sandy coastal soils across Mullaloo, Joondalup and northern coastal suburbs. Request a garden assessment and quote.",
    hero: true,
    content: `
      <section class="hero" style="--hero:url('/assets/perth-coastal-garden-hero.webp')">
        <div class="container"><div class="hero-content">
          <p class="eyebrow">Mullaloo Joondalup and Perth northern coast</p>
          <h1>Give your sandy coastal garden a better foundation</h1>
          <p>Garden rejuvenation, soil improvement and waterwise landscaping for established homes across Perth's northern coastal suburbs.</p>
          <div class="hero-actions"><a class="button sand" href="#quote">Request a quote</a><a class="button secondary" href="${phoneLink}">Call ${phone}</a></div>
        </div></div>
      </section>
      <section class="section"><div class="container split">
        <div><p class="eyebrow" style="color:#4f7462">Built around local conditions</p><h2>Perth sand changes how a garden should be planned</h2>
        <p>Fast-draining sandy ground, exposed coastal positions and dry summers can leave lawns patchy and garden beds struggling. A lasting update begins below the surface, with the existing soil, watering and plant choices considered together.</p>
        <ul class="check-list"><li>Rejuvenation for tired and dated gardens</li><li>Practical sandy-soil improvement</li><li>Waterwise planting suited to coastal exposure</li><li>Reticulation assessment where required</li></ul>
        <a class="button secondary" href="/services/sandy-soil-improvement/">Understand sandy-soil improvement</a></div>
        <figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Garden worker examining pale sandy soil beside organic soil improver in a coastal Perth garden" width="1536" height="1024" loading="lazy"></figure>
      </div></section>
      <section class="section white"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Ways to update your garden</p><h2>Start with the problem you can see</h2><p>From a complete refresh to one difficult part of the garden, the enquiry should begin with what is failing and how you want to use the space.</p></div>
        <div class="grid three">
          ${serviceCard('Garden rejuvenation','Refresh overgrown, dated or poorly performing gardens without assuming everything must be removed.','/services/garden-rejuvenation/')}
          ${serviceCard('Sandy-soil improvement','Prepare garden beds and planting areas with a site-specific approach to Perth sand.','/services/sandy-soil-improvement/')}
          ${serviceCard('Waterwise landscaping','Plan planting, mulch and watering around Perth conditions and the way you maintain your garden.','/services/waterwise-landscaping/')}
          ${serviceCard('Reticulation upgrades','Review uneven coverage, old controls and watering zones as part of a broader garden update.','/services/reticulation-upgrades/')}
          ${serviceCard('Lawn and garden-bed renewal','Address patchy lawn, tired edging and beds that no longer suit the home.','/services/')}
          ${serviceCard('Coastal planting','Choose planting with wind, salt exposure, sun and available space in mind.','/services/')}
        </div>
      </div></section>
      ${ctaBand('Is your garden ready for an update?','Tell us what is struggling and where the property is located.')}
      <section class="section"><div class="container split reverse">
        <figure class="media-frame"><img src="/assets/sandy-garden-before.webp" alt="Established northern Perth backyard with pale exposed sand patchy lawn and tired garden beds" width="1536" height="1024" loading="lazy"></figure>
        <div><p class="eyebrow" style="color:#4f7462">Honest starting points</p><h2>A struggling garden does not need to look abandoned</h2><p>Exposed sand, thin lawn and tired planting are common enough. The aim is to understand which parts can be retained, what needs attention first and whether the project should be completed at once or in stages.</p><p class="notice">Images on this website illustrate local conditions and design ideas. They are not presented as completed client projects.</p></div>
      </div></section>
      <section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">A clear enquiry process</p><h2>Useful information before promises</h2></div><div class="grid three">
        ${plainCard('1. Describe the garden','Share the suburb, problem areas, preferred outcome and approximate timing.')}
        ${plainCard('2. Add useful context','Photos, access details and the size of the area help clarify the likely scope.')}
        ${plainCard('3. Discuss the next step','Your enquiry can be matched with an appropriate service provider for a site-specific discussion.')}
      </div></div></section>
      <section class="section white"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">Distinctly Western Australian</p><h2>Ideas grounded in Perth planting</h2><p>Banksias, grass trees, kangaroo paws, silver foliage and warm limestone can create a garden with a strong local character. Plant selection still depends on the property's exposure, irrigation, soil and available space.</p><a class="text-link" href="/faq/">Read garden planning questions</a></div><figure class="media-frame short"><img src="/assets/kings-park-inspired.webp" alt="Western Australian native planting inspired by Perth botanic gardens" width="1536" height="1024" loading="lazy"></figure></div></section>
      ${formSection('Request a garden rejuvenation quote')}
    `
  },
  {
    path: 'services/index.html', nav: 'services', title: 'Coastal Garden Services Perth',
    description: "Explore garden rejuvenation, sandy soil improvement, waterwise landscaping and reticulation upgrade enquiries across Perth's northern coastal suburbs.",
    content: `${pageHero('Services','Garden improvements designed around Perth sand','Explore practical options for tired gardens, exposed coastal sites and planting areas that are difficult to keep healthy.','/assets/perth-waterwise-outdoor-living.webp')}
      <section class="section"><div class="container"><div class="intro"><h2>Choose the service that matches the problem</h2><p>A project may combine several services. Final recommendations and availability depend on a site assessment and the selected contractor's capabilities.</p></div><div class="grid two">
      ${serviceCard('Complete garden rejuvenation','Renew established gardens through selective removal, soil preparation, garden-bed updates, planting, mulch and related improvements.','/services/garden-rejuvenation/')}
      ${serviceCard('Sandy-soil improvement','Address the growing foundation before investing in new plants or lawn.','/services/sandy-soil-improvement/')}
      ${serviceCard('Waterwise landscaping','Plan a garden around suitable plants, healthy soil, mulch and more efficient watering.','/services/waterwise-landscaping/')}
      ${serviceCard('Reticulation assessment and upgrades','Review coverage, zoning, leaks and controls where irrigation affects the garden update.','/services/reticulation-upgrades/')}
      ${serviceCard('Lawn replacement and preparation','Consider the lawn and the soil beneath it rather than simply covering the same problem.','/contact/')}
      ${serviceCard('Garden beds and coastal planting','Renew tired beds with plants considered for sun, wind, salt exposure and maintenance needs.','/contact/')}
      </div></div></section>${ctaBand('Unsure where to begin?','Describe what is struggling and we can start with the most relevant discussion.')}${formSection('Discuss your garden project')}`
  },
  servicePage('garden-rejuvenation','Garden Rejuvenation Perth Northern Suburbs','Garden rejuvenation','Refresh a tired coastal garden without assuming everything has to be replaced.',
    ['Overgrown or dated garden beds','Patchy lawns and exposed sand','Planting that no longer suits the site','Front gardens that detract from the home','A garden that has become too difficult to maintain'],
    'A rejuvenation can combine selective clearing, soil preparation, retained planting, renewed beds, lawn work, mulch and watering improvements. The right scope depends on access, condition, budget and what you want to keep.',
    '/assets/sandy-garden-before.webp'),
  servicePage('sandy-soil-improvement','Sandy Soil Improvement Perth Gardens','Sandy-soil improvement','Give new planting a more considered foundation in Perth sand.',
    ['Water runs through the ground quickly','Dry soil is difficult to wet evenly','Plants struggle despite regular watering','Garden beds need preparation before replanting','Lawn remains thin or patchy'],
    'Water Corporation identifies organic matter, suitable soil improvers and wetting agents as possible tools for sandy soil. The correct combination is site-specific and should be assessed before treatment.',
    '/assets/sandy-soil-improvement.webp'),
  servicePage('waterwise-landscaping','Waterwise Landscaping Perth Northern Suburbs','Waterwise landscaping','Create a lower-demand coastal garden without reducing it to gravel and a few plants.',
    ['Plants with very different watering needs are mixed together','The garden relies on frequent watering','Bare soil loses moisture quickly','The existing layout is difficult to maintain','You want more locally appropriate planting'],
    'Waterwise planning considers soil health, mulch, plant grouping, exposure and irrigation together. It does not promise that a garden will need no water or maintenance.',
    '/assets/perth-waterwise-outdoor-living.webp'),
  servicePage('reticulation-upgrades','Reticulation Upgrades Joondalup and Mullaloo','Reticulation assessment and upgrades','Review watering coverage as part of a broader garden rejuvenation.',
    ['Some areas remain dry while others are overwatered','Old controls are difficult to adjust','Garden zones have changed since installation','Leaks or damaged components are visible','New planting needs a different watering approach'],
    'Reticulation work should match the garden zones, soil and plant needs. Specialist or regulated work must be completed by an appropriately capable provider.',
    '/assets/perth-reticulation-garden.webp'),
  {
    path: 'locations/index.html', nav: 'locations', title: 'Garden Rejuvenation Perth Northern Coastal Suburbs',
    description: 'Garden rejuvenation enquiries across Mullaloo, Joondalup, Ocean Reef, Kallaroo, Iluka, Hillarys and nearby northern coastal suburbs.',
    content: `${pageHero('Locations','Perth northern coastal gardens','Mullaloo is the local anchor, with enquiries welcomed from the connected Joondalup and northern coastal corridor.','/assets/perth-coastal-sandscape.webp')}
    <section class="section"><div class="container split"><div><h2>Initial enquiry area</h2><p>The focused service area keeps the site relevant to the sandy coastal conditions it discusses. Availability will depend on the eventual contractor, project size and travel requirements.</p><ul class="location-list">${['Mullaloo','Kallaroo','Ocean Reef','Iluka','Joondalup','Hillarys','Sorrento','Duncraig','Currambine','Kinross','Burns Beach','Mindarie','Quinns Rocks','Jindalee','North Beach','Carine','Craigie','Heathridge','Beldon','Woodvale'].map(x=>`<li>${x==='Mullaloo'?`<a href="/locations/mullaloo/">${x}</a>`:x==='Joondalup'?`<a href="/locations/joondalup/">${x}</a>`:`<span class="card" style="display:inline-block;padding:.5rem .8rem">${x}</span>`}</li>`).join('')}</ul></div><figure class="media-frame short"><img src="/assets/perth-coastal-sandscape.webp" alt="Western Australian coastal planting overlooking pale beach sand and the Indian Ocean" width="1280" height="720" loading="lazy"></figure></div></section>${ctaBand('Is your suburb nearby?','Send the property location and project outline so coverage can be confirmed.')}${formSection('Ask about your suburb')}`
  },
  locationPage('mullaloo','Garden Rejuvenation Mullaloo','Mullaloo garden rejuvenation','Mullaloo gardens sit squarely within the sandy coastal conditions this site addresses. Exposed front gardens, pale sand, ageing beds and patchy lawns can all form part of a rejuvenation brief.','/assets/mullaloo-coastal-front-garden.webp','/assets/perth-coastal-sandscape.webp'),
  locationPage('joondalup','Garden Rejuvenation Joondalup','Joondalup garden rejuvenation','Joondalup and its surrounding suburbs include established gardens, newer coastal homes and a wide range of outdoor spaces. Enquiries can cover soil preparation, planting, lawn, mulch and irrigation as one coordinated project.','/assets/kings-park-inspired.webp','/assets/perth-waterwise-outdoor-living.webp'),
  {
    path: 'about/index.html', nav: 'about', title: 'About Perth Coastal Gardens',
    description: "Perth Coastal Gardens connects northern coastal homeowners with garden rejuvenation enquiries focused on sandy soil and local conditions.",
    content: `${pageHero('About','Local garden information without invented claims','Perth Coastal Gardens is an independently owned lead-generation website focused on garden rejuvenation across Perth’s northern coastal suburbs.','/assets/kings-park-inspired.webp')}
    <section class="section"><div class="container split"><div><h2>Why the site begins with sand</h2><p>Perth's northern coastal gardens cannot be understood only from the plants visible above ground. Pale sand, water movement, wind exposure, existing irrigation and maintenance expectations all affect what should happen next.</p><p>This website helps homeowners describe their project and request contact from a suitable service provider. Contractor-specific details will be published only after they are confirmed.</p><h3>What you will not find here</h3><ul class="check-list"><li>Invented project numbers or years in business</li><li>Fabricated testimonials or star ratings</li><li>Unverified licences, guarantees or response times</li><li>Images falsely described as completed projects</li></ul></div><figure class="media-frame"><img src="/assets/sandy-soil-improvement.webp" alt="Sandy soil being assessed in a northern Perth coastal garden" width="1536" height="1024" loading="lazy"></figure></div></section>${ctaBand('Have a garden problem to discuss?','Share enough detail for a relevant first conversation.')}${formSection('Tell us about your garden')}`
  },
  {
    path: 'faq/index.html', nav: 'faq', title: 'Perth Sandy Soil and Garden Rejuvenation FAQ',
    description: "Answers about sandy soil, garden rejuvenation, waterwise planting, reticulation and quotes across Perth's northern coastal suburbs.",
    content: `${pageHero('Frequently asked questions','Planning a garden update on Perth sand','Straight answers to common questions before requesting a project discussion.','/assets/perth-coastal-sandscape.webp')}
    <section class="section"><div class="container faq">${faqItems()}</div></section>${ctaBand('Still unsure what your garden needs?','Describe the problem rather than trying to diagnose everything first.')}${formSection('Ask about your garden')}`
  },
  {
    path: 'contact/index.html', nav: 'contact', title: 'Contact Perth Coastal Gardens',
    description: 'Request a garden rejuvenation quote for Mullaloo, Joondalup or nearby Perth northern coastal suburbs. Call 0490 008 212 or enquire online.',
    content: `${pageHero('Contact','Start with the garden you have now','Tell us the suburb, the parts that are struggling and what you would like to change.','/assets/mullaloo-coastal-front-garden.webp')}
    <section class="section"><div class="container form-wrap"><div><p class="eyebrow" style="color:#4f7462">Contact details</p><h2>Discuss your garden</h2><p><strong>Phone</strong><br><a href="${phoneLink}">${phone}</a></p><p><strong>Email</strong><br><a href="mailto:${email}">${email}</a></p><p>Online enquiries can be submitted at any time. Attendance and phone hours will be confirmed when a service provider responds.</p><p class="notice">Perth Coastal Gardens is an online enquiry and referral website. No physical storefront is represented.</p></div>${formCard('Garden project enquiry')}</div></section>`
  },
  {
    path: 'blog/index.html', nav: 'blog', title: 'Perth Coastal Garden Advice',
    description: "Practical guides to garden rejuvenation, sandy soil and waterwise landscaping for Perth's northern coastal suburbs.",
    content: `${pageHero('Garden advice','Useful guidance for Perth coastal gardens','Start with the soil, exposure and the way you want to use the garden—not a generic plant list.','/assets/kings-park-inspired.webp')}
    <section class="section"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Resource library</p><h2>Plan before you replace</h2><p>These guides explain common decisions for established gardens on Perth's sandy coastal plain. They provide general information; the right solution still depends on the property.</p></div><div class="grid three">
    ${articleCard('How to improve sandy soil in a Perth garden','A practical look at organic matter, wetting, mulch and realistic expectations.','/blog/improving-sandy-soil-perth-gardens/','/assets/sandy-soil-improvement.webp')}
    ${articleCard('What affects the cost of garden rejuvenation?','Understand the site and scope factors that shape a useful quotation.','/blog/garden-rejuvenation-cost-perth/','/assets/sandy-garden-before.webp')}
    ${articleCard('Planning a waterwise coastal garden','Bring soil, plant grouping, exposure, mulch and irrigation into one plan.','/blog/waterwise-coastal-garden-perth/','/assets/kings-park-inspired.webp')}
    </div></div></section>${ctaBand('Need advice for your own garden?','Share the suburb, current condition and the result you have in mind.')}`
  },
  blogPage('improving-sandy-soil-perth-gardens','How to Improve Sandy Soil in a Perth Garden','Sandy soil can be improved, but lasting results usually come from treating soil structure, water movement, mulch and planting as one system.','/assets/sandy-soil-improvement.webp',`
    <h2>Why Perth sand needs a different approach</h2><p>Much of Perth's coastal plain has deep, fast-draining sandy soil. Water and soluble nutrients may move beyond shallow roots quickly, while dry areas can become difficult to wet evenly. Adding plants without preparing the growing area can repeat the same cycle of stress and replacement.</p>
    <h2>Begin with the condition of the site</h2><p>Check whether water soaks in evenly or runs away, where sun and coastal wind are strongest, and whether existing irrigation reaches the root zone. Plant decline can have more than one cause, so soil improvement should not be treated as a single-product cure.</p>
    <h2>Organic matter and soil improvers</h2><p>Well-composted organic matter can help sandy soil retain moisture and nutrients. Suitable clay-based soil improvers may also be considered. Products and rates should be selected for the intended planting and applied according to their directions; more is not automatically better.</p>
    <h2>Wetting agents, mulch and watering</h2><p>A suitable wetting agent may help where dry soil repels water. Mulch can reduce evaporation and temperature swings, while irrigation should deliver water to the correct zone without encouraging waste. These measures work best as part of a planned improvement rather than isolated treatments.</p>
    <h2>What should happen before planting?</h2><ol><li>Identify drainage, exposure and irrigation issues.</li><li>Remove weeds and unsuitable material.</li><li>Prepare the planting zone rather than a tiny planting hole.</li><li>Incorporate suitable amendments where required.</li><li>Choose plants for the finished conditions.</li><li>Mulch and establish an appropriate watering routine.</li></ol>
    <div class="source-note"><strong>Useful source:</strong> Water Corporation provides Western Australian guidance on <a href="https://www.watercorporation.com.au/Help-and-advice/Waterwise/Garden/Improve-your-soil" rel="noopener external">improving sandy soil</a>.</div>
    <h2>When should you request an assessment?</h2><p>Consider professional input when a large area repeatedly fails, irrigation and soil issues overlap, or the project involves a broader redesign. A site assessment can help avoid spending on plants before the foundation is ready.</p>`),
  blogPage('garden-rejuvenation-cost-perth','What Affects Garden Rejuvenation Costs in Perth?','Garden rejuvenation does not have one reliable square-metre price. Access, removal, soil preparation, planting, irrigation and the amount retained all influence the scope.','/assets/sandy-garden-before.webp',`
    <h2>The existing garden is part of the quotation</h2><p>A clear, accessible site with useful plants to retain is different from an overgrown garden requiring extensive removal. Mature roots, old edging, waste volume and restricted side access can affect labour and disposal before new work begins.</p>
    <h2>Soil preparation can be the hidden foundation</h2><p>In Perth's sandy coastal suburbs, a quote that considers only visible finishes may miss the work below them. Garden beds, lawns and new planting may require different preparation, and irrigation problems can need attention before the new layout is installed.</p>
    <h2>Plants, materials and establishment</h2><p>Plant size, species, quantities, mulch, edging, lawn and feature materials all change the project total. Smaller plants can reduce the initial supply cost but take longer to establish the intended look. The right balance depends on budget, timing and maintenance expectations.</p>
    <h2>How to obtain a more useful quote</h2><ul><li>Explain what you want to retain as well as remove.</li><li>Provide clear photos and approximate dimensions.</li><li>Mention access limitations and known reticulation issues.</li><li>Separate essential work from optional features.</li><li>Say whether the project can be staged.</li></ul>
    <h2>Can garden rejuvenation be completed in stages?</h2><p>Often it can. Soil and irrigation planning should still consider the whole property so that early work does not conflict with later stages. A front garden, entertaining area or most difficult planting zone can then become a logical first phase.</p>
    <h2>Avoid unsupported price promises</h2><p>Online figures can be a rough prompt, but they cannot account for site condition, contractor scope or material choices. A property-specific discussion is the safest basis for decisions and comparison.</p>`),
  blogPage('waterwise-coastal-garden-perth','How to Plan a Waterwise Coastal Garden in Perth','A waterwise garden is a coordinated plan for soil, plants, mulch and irrigation—not a promise of a water-free landscape.','/assets/kings-park-inspired.webp',`
    <h2>Start with exposure and usable space</h2><p>Coastal wind, salt, reflected heat and full western sun can create very different growing conditions within one property. Map these areas before selecting plants, and keep practical access, outdoor living and views in the plan.</p>
    <h2>Improve the soil before reducing water</h2><p>Fast-draining sand can limit the benefit of efficient irrigation if the root zone has not been prepared. Suitable organic matter, soil improvers and mulch can help water remain available for longer. The exact approach depends on the existing site.</p>
    <h2>Group plants with compatible needs</h2><p>Hydrozoning places plants with similar water requirements together. This makes it easier to water appropriately and avoids maintaining thirsty plants and low-water plants on the same schedule.</p>
    <h2>Use Western Australian character thoughtfully</h2><p>Banksias, kangaroo paws, native grasses and silver foliage can contribute colour and texture, but no plant should be selected from appearance alone. Mature size, drainage, wind tolerance and the home's architecture matter too.</p>
    <h2>Review irrigation as the garden changes</h2><p>Old sprinkler positions may no longer match reshaped beds or maturing plants. Review coverage, leaks, zoning and controller settings, and use appropriately qualified help where work requires it.</p>
    <div class="source-note"><strong>Useful source:</strong> The Waterwise program provides local information about <a href="https://www.watercorporation.com.au/Help-and-advice/Waterwise/Garden" rel="noopener external">waterwise gardening in Western Australia</a>.</div>
    <h2>What does a good plan achieve?</h2><p>The result should suit the household as well as the climate: clear circulation, useful outdoor areas, manageable maintenance, healthier planting and a watering approach matched to each zone.</p>`),
  {
    path: 'privacy/index.html', nav: '', title: 'Privacy Policy Perth Coastal Gardens',
    description: 'Privacy information for Perth Coastal Gardens enquiries, referrals and website analytics.',
    content: `${simpleHero('Privacy policy','How enquiry information is collected and used.')}
    <section class="section white"><div class="container" style="max-width:850px"><h2>Information collected</h2><p>When you submit an enquiry, this website may collect your name, email, phone number, suburb, service interest and project message. Basic website usage information may also be collected through analytics and security services.</p><h2>Why it is collected</h2><p>Information is used to respond to your request, assess whether the enquiry matches the service area and refer the request to a suitable service provider where appropriate.</p><h2>Enquiry referrals</h2><p>By submitting a service enquiry, you understand that relevant details may be shared with a service provider so that they can contact you about the requested work. Information is not sold as a general marketing list.</p><h2>Email and forms</h2><p>Messages may be processed by email-forwarding and form-delivery providers. Do not send highly sensitive personal information through the website.</p><h2>Your choices</h2><p>You may ask about the information associated with your enquiry or request correction or deletion where applicable by emailing <a href="mailto:${email}">${email}</a>.</p><h2>General information</h2><p>Garden information on this website is general. A site-specific assessment is required before choosing treatments, materials or planting.</p></div></section>`
  },
  legalPage('terms','Terms of Use','These terms explain the role of Perth Coastal Gardens as an online enquiry and referral website.',`<h2>Website role</h2><p>Perth Coastal Gardens publishes general garden information and receives service enquiries. It does not represent a physical storefront or guarantee that a particular contractor will be available.</p><h2>Quotes and agreements</h2><p>Any inspection, scope, price, timing, warranty or service agreement must be confirmed directly with the service provider. Submitting an enquiry does not create a contract for work.</p><h2>Information accuracy</h2><p>Reasonable care is taken with website content, but garden conditions vary. Information may be updated and should not replace property-specific advice.</p><h2>Acceptable use</h2><p>Do not misuse the forms, attempt to interfere with the website, or submit unlawful or misleading material.</p><h2>Contact</h2><p>Questions about these terms may be emailed to <a href="mailto:${email}">${email}</a>.</p>`),
  legalPage('disclaimer','Website Disclaimer','Important limits applying to garden information, images and service enquiries.',`<h2>General information only</h2><p>Content is educational and general. Soil, drainage, irrigation, plants and site conditions should be assessed before work or purchasing decisions.</p><h2>Illustrative images</h2><p>Current photographs illustrate local conditions and design ideas. They are not represented as projects completed by Perth Coastal Gardens or a future service provider.</p><h2>No unsupported promises</h2><p>This website does not promise a particular result, response time, price, licence status, warranty or availability. Contractor-specific claims will be published only after verification.</p><h2>External sources</h2><p>Links to external information are provided for convenience. Their owners control and may update that content.</p>`),
  {
    path: 'thank-you/index.html', nav: '', title: 'Thank You Perth Coastal Gardens', noindex: true,
    description: 'Your Perth Coastal Gardens enquiry has been submitted.',
    content: `${simpleHero('Thank you','Your enquiry has been submitted. Please keep a copy of any photographs or project details you may wish to discuss.')}
    <section class="section"><div class="container" style="text-align:center"><a class="button" href="/">Return home</a></div></section>`
  },
  {
    path: '404.html', nav: '', title: 'Page Not Found Perth Coastal Gardens', noindex: true,
    description: 'The requested page could not be found.',
    content: `${simpleHero('Page not found','The address may have changed or the page may no longer be available.')}
    <section class="section"><div class="container" style="text-align:center"><a class="button" href="/">Return home</a></div></section>`
  }
];

function serviceCard(title, text, href) { return `<article class="card"><h3>${title}</h3><p>${text}</p><a class="text-link" href="${href}">Learn more</a></article>`; }
function articleCard(title,text,href,image) { return `<article class="article-card"><a href="${href}" aria-label="Read ${title}"><img src="${image}" alt="${title}" width="1536" height="1024" loading="lazy"></a><div><p class="eyebrow" style="color:#4f7462">Garden guide</p><h3><a href="${href}">${title}</a></h3><p>${text}</p><a class="text-link" href="${href}">Read the guide</a></div></article>`; }
function plainCard(title, text) { return `<article class="card"><h3>${title}</h3><p>${text}</p></article>`; }
function ctaBand(title, text) { return `<section class="band"><div class="container band-inner"><div><h2>${title}</h2><p>${text}</p></div><div class="cta-actions"><a class="button" href="/contact/">Request a quote</a><a class="button secondary" style="border-color:white;color:white!important" href="${phoneLink}">Call ${phone}</a></div></div></section>`; }
function pageHero(label, title, text, image) { return `<section class="page-hero has-image" style="--page-image:url('${image}')"><div class="container"><div class="crumbs"><a href="/">Home</a> / ${label}</div><p class="eyebrow">Perth Coastal Gardens</p><h1>${title}</h1><p>${text}</p><div class="hero-actions"><a class="button sand" href="/contact/">Request a quote</a><a class="button secondary" href="${phoneLink}">Call ${phone}</a></div></div></section>`; }
function simpleHero(title,text) { return `<section class="page-hero"><div class="container"><h1>${title}</h1><p>${text}</p></div></section>`; }
function formCard(subject) { return `<div class="form-card"><form action="https://formsubmit.co/${email}" method="POST"><input type="hidden" name="_subject" value="${subject} from perthcoastgardens.com"><input type="hidden" name="_next" value="${domain}/thank-you/"><input type="text" name="_honey" class="form-honey" tabindex="-1" autocomplete="off"><label>Name<input name="name" type="text" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Phone<input name="phone" type="tel" autocomplete="tel" required></label><label>Suburb or postcode<input name="suburb" type="text" autocomplete="postal-code" required></label><label class="full">Service needed<select name="service" required><option value="">Choose one</option><option>Garden rejuvenation</option><option>Sandy-soil improvement</option><option>Waterwise landscaping</option><option>Reticulation assessment</option><option>Lawn or garden-bed renewal</option><option>Unsure</option></select></label><label class="full">Message<textarea name="message" required placeholder="What is struggling, what would you like to change, and when are you hoping to begin?"></textarea></label><p class="form-note">By submitting this form, you agree that your enquiry may be shared with a suitable service provider so they can contact you about the requested work. See the <a href="/privacy/">privacy policy</a>.</p><button type="submit">Send garden enquiry</button></form></div>`; }
function formSection(title) { return `<section class="section" id="quote"><div class="container form-wrap"><div><p class="eyebrow" style="color:#4f7462">Your garden and location</p><h2>${title}</h2><p>Share the suburb, visible problems and the result you would like. Photos can be discussed after the initial enquiry.</p><p><strong>Prefer to call?</strong><br><a href="${phoneLink}">${phone}</a></p></div>${formCard(title)}</div></section>`; }
function relatedSection(context='service') { return `<section class="section cream"><div class="container"><div class="intro"><p class="eyebrow" style="color:#4f7462">Continue planning</p><h2>Related local garden information</h2><p>Follow the subject that best matches your property, then use the enquiry page when you are ready to discuss the site.</p></div><nav class="related-grid" aria-label="Related garden information">
  ${context!=='service'?'<a href="/services/garden-rejuvenation/"><strong>Garden rejuvenation</strong><span>Plan a coordinated update</span></a>':''}
  <a href="/services/sandy-soil-improvement/"><strong>Sandy-soil improvement</strong><span>Prepare the growing foundation</span></a>
  <a href="/services/waterwise-landscaping/"><strong>Waterwise landscaping</strong><span>Plan planting and watering together</span></a>
  <a href="/locations/mullaloo/"><strong>Garden rejuvenation in Mullaloo</strong><span>Local coastal garden context</span></a>
  <a href="/locations/joondalup/"><strong>Garden rejuvenation in Joondalup</strong><span>Services across the Joondalup area</span></a>
  <a href="/blog/"><strong>Perth coastal garden advice</strong><span>Read practical planning guides</span></a>
</nav></div></section>`; }
function servicePage(slug,title,label,lead,issues,body,image) { return { path:`services/${slug}/index.html`, nav:'services', title, description:`${label} for sandy coastal gardens across Mullaloo, Joondalup and Perth's northern suburbs. Request a project discussion and quote.`, content:`${pageHero('Services',label,lead,image)}<section class="section"><div class="container split"><div><p class="eyebrow" style="color:#4f7462">When this may help</p><h2>Start with what is happening now</h2><ul class="check-list">${issues.map(x=>`<li>${x}</li>`).join('')}</ul><p>${body}</p><p>For broader planning, compare all <a href="/services/">Perth coastal garden services</a> or read the guide to <a href="/blog/improving-sandy-soil-perth-gardens/">improving sandy soil before planting</a>.</p></div><figure class="media-frame"><img src="${image}" alt="${label} in a sandy northern coastal Perth garden" width="1536" height="1024" loading="lazy"></figure></div></section>${ctaBand('Discuss the next step for your garden','A useful quote begins with the property, scope and current condition.')}${relatedSection('service')}${formSection(`Request a ${label.toLowerCase()} quote`)}`}; }
function locationPage(slug,title,label,text,heroImage='/assets/sandy-garden-before.webp',bodyImage='/assets/perth-coastal-garden-hero.webp') { const place=label.replace(' garden rejuvenation',''); return { path:`locations/${slug}/index.html`, nav:'locations', title, description:`${label} enquiries for sandy soil improvement, waterwise planting and established garden updates in Perth's northern coastal suburbs.`, content:`${pageHero('Locations',label,text,heroImage)}<section class="section"><div class="container split"><div><h2>Garden updates suited to ${place}</h2><p>${text}</p><ul class="check-list"><li><a href="/services/garden-rejuvenation/">Complete garden rejuvenation</a></li><li><a href="/services/sandy-soil-improvement/">Sandy-soil and garden-bed improvement</a></li><li><a href="/services/waterwise-landscaping/">Waterwise and coastal planting</a></li><li><a href="/services/reticulation-upgrades/">Lawn and reticulation considerations</a></li></ul><p>Availability and the final scope must be confirmed for the property and selected service provider. See the <a href="/locations/">full northern coastal service area</a> or read <a href="/blog/garden-rejuvenation-cost-perth/">what affects a garden rejuvenation quote</a>.</p></div><figure class="media-frame"><img src="${bodyImage}" alt="Waterwise coastal garden suited to a ${place} area home" width="1536" height="1024" loading="lazy"></figure></div></section>${ctaBand(`Planning a garden update in ${place}?`,'Send the project outline and property location for a relevant discussion.')}${relatedSection('location')}${formSection(`Request a quote in ${place}`)}`}; }
function blogPage(slug,title,answer,image,body) { return {path:`blog/${slug}/index.html`,nav:'blog',title,description:answer,article:true,content:`${pageHero('Garden advice',title,answer,image)}<article class="section white"><div class="container article"><p class="article-meta">Perth Coastal Gardens · General garden guidance · Updated September 2026</p><p class="answer-block"><strong>In brief:</strong> ${answer}</p>${body}<aside class="article-cta"><h2>Discuss your own garden</h2><p>General guidance is a starting point. Explore <a href="/services/">garden rejuvenation services</a>, check the <a href="/locations/">northern coastal service area</a>, or share your suburb and current garden condition.</p><a class="button" href="/contact/">Request a discussion</a></aside></div></article>${relatedSection('article')}${formSection('Request a garden project quote')}`}; }
function legalPage(slug,title,intro,body) { return {path:`${slug}/index.html`,nav:'',title:`${title} Perth Coastal Gardens`,description:intro,content:`${simpleHero(title,intro)}<section class="section white"><div class="container article">${body}</div></section>`}; }
function faqItems() { const items=[['Why do gardens struggle in Perth sand?','Sandy ground may drain quickly and retain less moisture and nutrients. Existing soil, plants, watering and exposure should be considered together.'],['Can sandy soil be improved?','Often, yes. Organic matter, suitable soil improvers, wetting agents, mulch and watering changes may be considered after assessing the site.'],['What is garden rejuvenation?','It refreshes an existing garden through a combination of selective clearing, soil preparation, renewed beds, planting, lawn, mulch and watering improvements.'],['Is rejuvenation different from regular gardening?','Regular gardening maintains what is already there. Rejuvenation addresses a garden that is struggling, dated, overgrown or poorly suited to the household.'],['What makes a garden waterwise?','Plant choice, soil health, mulch, grouping and efficient irrigation work together. Waterwise does not mean maintenance-free or water-free.'],['Which plants suit coastal gardens?','That depends on wind, salt exposure, sun, drainage and available space. Final selections should follow a site assessment.'],['Can only part of the garden be updated?','Yes. Many projects can be staged, beginning with a front garden, difficult bed, lawn or watering problem.'],['Do all existing plants need to be removed?','Not necessarily. A good assessment identifies what may be retained, moved, pruned or replaced.'],['How much does a garden makeover cost?','Cost depends on area, access, removal, soil preparation, plants, irrigation, lawn and construction. A project-specific quote is more useful than an unsupported fixed figure.'],['Do you service my suburb?','The initial enquiry area covers Mullaloo, Joondalup and selected northern coastal suburbs. Exact availability must be confirmed.'],['Are quotes free?','The quoting policy depends on the service provider. Request a discussion without assuming every design visit or detailed assessment is free.'],['Are the photographs completed projects?','No. Current website photographs illustrate local conditions and design ideas and are not presented as client projects.']]; return items.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join(''); }

function header(current) {
  const link=(key,href,label)=>`<a href="${href}" ${current===key?'aria-current="page"':''}>${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"></span><span>Perth Coastal Gardens</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav class="nav" id="site-nav" aria-label="Primary">${link('home','/','Home')}${link('services','/services/','Services')}${link('locations','/locations/','Locations')}${link('blog','/blog/','Advice')}${link('about','/about/','About')}${link('faq','/faq/','FAQ')}${link('contact','/contact/','Contact')}<a class="button header-call" href="${phoneLink}">${phone}</a></nav></div></header>`;
}
function footer() { return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><h2>Perth Coastal Gardens</h2><p>Garden rejuvenation enquiries for sandy soils across Perth's northern coastal suburbs.</p><p><a href="${phoneLink}">${phone}</a><br><a href="mailto:${email}">${email}</a></p></div><div><h3>Explore</h3><ul><li><a href="/services/">Garden services</a></li><li><a href="/locations/">Service areas</a></li><li><a href="/blog/">Garden advice</a></li><li><a href="/faq/">Frequently asked questions</a></li></ul></div><div><h3>Information</h3><ul><li><a href="/about/">About this website</a></li><li><a href="/contact/">Contact</a></li><li><a href="/privacy/">Privacy policy</a></li><li><a href="/terms/">Terms of use</a></li><li><a href="/disclaimer/">Disclaimer</a></li></ul></div></div><div class="legal"><span>© <span data-year></span> Perth Coastal Gardens</span><span>Online enquiry and referral website. No physical storefront represented.</span></div></div></footer>`; }
function schema(page,url) { const graph=[{'@type':'WebSite','@id':`${domain}/#website`,url:domain,name:'Perth Coastal Gardens',inLanguage:'en-AU',description:'Garden rejuvenation information and enquiries for Perth northern coastal suburbs'},{'@type':'Organization','@id':`${domain}/#organization`,name:'Perth Coastal Gardens',url:domain,email,telephone:'+61490008212',areaServed:['Mullaloo','Joondalup','Perth northern coastal suburbs']},{'@type':page.article?'Article':'WebPage','@id':`${url}#webpage`,url,name:page.title,isPartOf:{'@id':`${domain}/#website`},description:page.description,inLanguage:'en-AU',...(page.article?{author:{'@id':`${domain}/#organization`},publisher:{'@id':`${domain}/#organization`},dateModified:'2026-09-14'}:{})}]; return JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c'); }
function shell(page) { const clean=page.path==='index.html'?'':page.path.replace(/index\.html$/,''); const url=`${domain}/${clean}`; const title=`${page.title} | Perth Coastal Gardens`; return `<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${page.description}">${page.noindex?'<meta name="robots" content="noindex,follow">':''}<link rel="canonical" href="${url}"><meta property="og:type" content="${page.article?'article':'website'}"><meta property="og:locale" content="en_AU"><meta property="og:site_name" content="Perth Coastal Gardens"><meta property="og:title" content="${title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${page.description}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${schema(page,url)}</script></head><body>${header(page.nav)}<main id="main">${page.content}</main>${footer()}<script src="/app.js" defer></script></body></html>`; }

await rm('dist',{recursive:true,force:true});
await mkdir('dist/assets',{recursive:true});
for (const image of ['perth-coastal-garden-hero.webp','sandy-garden-before.webp','sandy-soil-improvement.webp','kings-park-inspired.webp','mullaloo-coastal-front-garden.webp','perth-coastal-sandscape.webp','perth-reticulation-garden.webp','perth-waterwise-outdoor-living.webp']) {
  await cp(join('src/assets', image), join('dist/assets', image));
}
await cp('src/styles.css','dist/styles.css');
await cp('src/app.js','dist/app.js');
for (const page of pages) { const out=join('dist',page.path); await mkdir(dirname(out),{recursive:true}); await writeFile(out,shell(page)); }
const urls=pages.filter(p=>!p.noindex&&p.path!=='404.html').map(p=>`${domain}/${p.path==='index.html'?'':p.path.replace(/index\.html$/,'')}`);
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/llms.txt',`# Perth Coastal Gardens\n\n> Garden rejuvenation information and enquiry website for Perth's northern coastal suburbs.\n\n## Core topics\n- Garden rejuvenation on sandy coastal soils\n- Sandy-soil improvement\n- Waterwise landscaping\n- Reticulation assessment and upgrades\n\n## Service area\nMullaloo, Joondalup and nearby northern coastal suburbs of Perth, Western Australia.\n\n## Key pages\n- ${domain}/services/\n- ${domain}/locations/\n- ${domain}/blog/\n- ${domain}/faq/\n- ${domain}/contact/\n\n## Contact\n- Phone: ${phone}\n- Email: ${email}\n\nImages illustrate local conditions and design ideas and are not represented as completed client projects. Contractor-specific claims must be confirmed directly.\n\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/llms-full.txt',`# Perth Coastal Gardens — detailed site guide\n\nPerth Coastal Gardens is an independently owned online lead-generation and garden-information website. It helps homeowners describe garden rejuvenation projects and request contact from a suitable service provider. It does not represent a physical storefront.\n\nThe editorial focus is the relationship between Perth's sandy coastal soils, water movement, planting, mulch, lawn and reticulation. Core service information covers complete garden rejuvenation, sandy-soil improvement, waterwise landscaping and reticulation assessment. Location information focuses on Mullaloo, Joondalup and the connected northern coastal corridor.\n\nThe Garden Advice library contains general educational guides. Property-specific assessment is required before selecting treatments, materials or plants. Current images are illustrative rather than portfolio evidence. No ratings, reviews, project totals, years in business, licence claims, response times or guarantees should be inferred unless later published with verification.\n\nAuthoritative navigation: ${domain}/services/ | ${domain}/locations/ | ${domain}/blog/ | ${domain}/faq/ | ${domain}/contact/\nContact: ${phone} | ${email}\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile('dist/_redirects',`https://www.perthcoastgardens.com/* https://perthcoastgardens.com/:splat 301\n`);
await writeFile('dist/favicon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#173642"/><path d="M12 38c12-4 18-15 25-24 7 14 15 21 15 31-7-7-15-10-24-9 7 3 13 8 17 15-14 1-25-3-33-13Z" fill="#4F7462"/><path d="M15 44c12-7 24-9 36-5" fill="none" stroke="#D9C7A3" stroke-width="5" stroke-linecap="round"/></svg>`);
console.log(`Built ${pages.length} pages`);
